# Generate Multispecies Slow-Mode Inputs

This notebook is the consolidated generation pipeline. It does the expensive stages only and saves reusable outputs:

1. load all-pair distance traces across species,
2. fit/reuse PCA before wavelets,
3. run wavelet transform and PCA after wavelets,
4. optionally assign microstates and compute slow modes from the saved projections.

Plotting and species-identity analyses live in separate notebooks so this file stays focused on generation.

## 1. Imports

In [1]:
from pathlib import Path
import gc
import importlib
import pickle
import sys
import warnings

import numpy as np
import pandas as pd
from sklearn.exceptions import InconsistentVersionWarning

REPO_ROOT = Path('/Users/meganbishop/slowmodeevo').resolve()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import all_pair_distance_data as apd
import pooled_user_pipeline as pup
pup = importlib.reload(pup)

## 2. Configuration

In [2]:
REPO_ROOT = Path('/Users/meganbishop/slowmodeevo').resolve()
DATAVERSE_ROOT = Path('/Users/meganbishop/moseq_dataverse')

RUN_NAME = 'pca_multispecies_evensamp'
OUTPUT_ROOT = REPO_ROOT / 'outputs/single_species_distance_comparison/'
RUN_ROOT = OUTPUT_ROOT / RUN_NAME
RUN_ROOT.mkdir(parents=True, exist_ok=True)

REPRESENTATION_NAME = 'egocentered_and_normalized_distances'
COORDINATE_DATASET = 'recording/egocentric_coordinates_rigid'
DATASET_NAME_AFTER_PRE_PCA = f'{REPRESENTATION_NAME}_pre_wavelet_pca'

SEED = 14
FS_HZ = 120.0
FMIN = 0.5
FMAX_CAP = 60.0
FMAX = min(FMAX_CAP, 0.45 * FS_HZ)
N_FREQS = 25

DISTANCE_PCA_VARIANCE_TARGET = 0.99
DISTANCE_PCA_MAX_COMPONENTS = 100
DISTANCE_PCA_SUBSAMPLE_FACTOR = 50
BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES = True
DISTANCE_PCA_ROWS_PER_SPECIES = None  # None uses the smallest species' available sample count.



POST_WAVELET_PCA_VARIANCE_TARGET = 0.99
POST_WAVELET_PCA_MAX_COMPONENTS = 100
WAVELET_SUBSAMPLE_FACTOR = 50
NORMALIZE_WAVELETS_FOR_PCA = True
BALANCE_POST_WAVELET_PCA_SAMPLES_BY_SPECIES = True
POST_WAVELET_PCA_ROWS_PER_SPECIES = None  # None uses the smallest species' available wavelet sample count.
POST_WAVELET_PCA_FIT_METHOD = 'streaming_covariance'
SAVE_WAVELET_SAMPLES = True 
REUSE_EXISTING = True

RUN_SLOW_MODES = True
D_EMBED = 10
N_CLUSTERS = 1000
KMEANS_SUBSAMPLE_FACTOR = 20
KMEANS_N_INIT = 20
TAU_SECONDS = 2.0
N_BASINS = 4
USE_RECURSIVE_ARMS = False

GLOBAL_ID_SEPARATOR = '__subject__'
print(f'RUN_ROOT = {RUN_ROOT}')

RUN_ROOT = /Users/meganbishop/slowmodeevo/outputs/single_species_distance_comparison/pca_multispecies_evensamp

## 3. Load Distance Data And Build Global IDs

In [3]:
distance_data = apd.AllPairDistanceData(DATAVERSE_ROOT)
base_loader = distance_data.make_loader(COORDINATE_DATASET, REPRESENTATION_NAME)

species_names = distance_data.available_species
rows = []
for species in species_names:
    for subject in distance_data.species_subjects(species):
        rows.append({
            'species': species,
            'individual_id': str(subject),
            'global_id': f'{species}{GLOBAL_ID_SEPARATOR}{subject}',
        })
individual_manifest = pd.DataFrame(rows)
individual_manifest.to_csv(RUN_ROOT / 'multispecies_individual_manifest.csv', index=False)

global_ids = individual_manifest['global_id'].tolist()
print(f'{len(species_names)} species, {len(global_ids)} individuals')
display(individual_manifest.groupby('species').size().rename('n_individuals').reset_index())

8 species, 354 individuals

                   species  n_individuals
0               Mus_caroli             15
1             Mus_musculus             93
2              Mus_spretus             16
3  Peromyscus_californicus             23
4    Peromyscus_gossypinus             20
5      Peromyscus_leucopus             14
6   Peromyscus_maniculatus            129
7    Peromyscus_polionotus             44

## 4. PCA Before Wavelet Transform

In [4]:
def parse_global_id(global_id):
    species, individual_id = str(global_id).split(GLOBAL_ID_SEPARATOR, 1)
    return species, individual_id


def distance_pca_config():
    return {
        'run_name': RUN_NAME,
        'representation_name': REPRESENTATION_NAME,
        'coordinate_dataset': COORDINATE_DATASET,
        'global_ids': list(global_ids),
        'distance_pca_variance_target': float(DISTANCE_PCA_VARIANCE_TARGET),
        'distance_pca_max_components': int(DISTANCE_PCA_MAX_COMPONENTS),
        'distance_pca_subsample_factor': int(DISTANCE_PCA_SUBSAMPLE_FACTOR),
        'balance_distance_pca_samples_by_species': bool(BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES),
        'distance_pca_rows_per_species': (
            None if DISTANCE_PCA_ROWS_PER_SPECIES is None else int(DISTANCE_PCA_ROWS_PER_SPECIES)
        ),
        'distance_pca_fit_method': DISTANCE_PCA_FIT_METHOD,
        'seed': int(SEED),
    }


def load_pickle(path):
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=InconsistentVersionWarning)
        with open(path, 'rb') as handle:
            return pickle.load(handle)


def _available_fixed_stride_rows(n_frames, factor):
    return len(np.arange(0, int(n_frames), max(1, int(factor)), dtype=int))


def _build_species_balanced_distance_pca_plan(sample_rows, rows_per_species=None):
    plan = pd.DataFrame(sample_rows).copy()
    species_available = plan.groupby('species')['available_sample_rows'].sum().sort_index()
    if species_available.empty:
        raise ValueError('No species available for distance PCA sampling')
    if (species_available <= 0).any():
        empty = species_available[species_available <= 0].index.tolist()
        raise ValueError(f'Species with no distance PCA sample rows: {empty}')
    target_rows = int(species_available.min() if rows_per_species is None else rows_per_species)
    target_rows = max(1, target_rows)
    plan['species_sample_budget'] = plan['species'].map(
        lambda species: min(target_rows, int(species_available.loc[species]))
    ).astype(int)
    plan['n_sample_rows'] = 0
    for species, sub in plan.groupby('species', sort=True):
        species_total = int(sub['available_sample_rows'].sum())
        species_budget = min(target_rows, species_total)
        exact = sub['available_sample_rows'].to_numpy(float) * species_budget / species_total
        take = np.floor(exact).astype(int)
        shortfall = int(species_budget - take.sum())
        if shortfall > 0:
            order = np.argsort(-(exact - take), kind='mergesort')[:shortfall]
            take[order] += 1
        take = np.minimum(take, sub['available_sample_rows'].to_numpy(int))
        shortfall = int(species_budget - take.sum())
        if shortfall > 0:
            spare = sub['available_sample_rows'].to_numpy(int) - take
            for local_idx in np.argsort(-spare, kind='mergesort'):
                if shortfall <= 0 or spare[local_idx] <= 0:
                    break
                add = min(shortfall, int(spare[local_idx]))
                take[local_idx] += add
                shortfall -= add
        plan.loc[sub.index, 'n_sample_rows'] = take
    return plan


def _select_distance_pca_rows(X, n_take, factor, rng):
    starts = np.arange(0, int(X.shape[0]), max(1, int(factor)), dtype=int)
    if n_take is None or int(n_take) >= starts.size:
        selected = starts
    else:
        selected = np.sort(rng.choice(starts, size=int(n_take), replace=False))
    return np.asarray(X[selected], dtype=np.float32)


def _iter_distance_pca_batches(sample_plan, *, seed):
    rng = np.random.default_rng(seed)
    for index, row in enumerate(sample_plan.itertuples(index=False), start=1):
        species = str(row.species)
        individual_id = str(row.individual_id)
        global_id = str(row.global_id)
        n_take = int(row.n_sample_rows)
        if n_take <= 0:
            continue
        bundle = base_loader(species, individual_id=individual_id, dataset_name=REPRESENTATION_NAME)
        X_sample = _select_distance_pca_rows(
            bundle['X'],
            n_take,
            DISTANCE_PCA_SUBSAMPLE_FACTOR,
            rng,
        )
        print(f'[{index}/{len(sample_plan)}] covariance sample {global_id}: {X_sample.shape}')
        yield X_sample
        del bundle, X_sample
        gc.collect()


def fit_or_load_distance_pca():
    checkpoint_path = RUN_ROOT / 'pre_wavelet_pca95_checkpoint.pkl'
    sample_manifest_path = RUN_ROOT / 'pre_wavelet_pca_sample_manifest.csv'
    balanced_plan_path = RUN_ROOT / 'pre_wavelet_pca_balanced_sample_plan.csv'
    config = distance_pca_config()
    if REUSE_EXISTING and checkpoint_path.exists():
        cached = load_pickle(checkpoint_path)
        cached_pca = cached.get('pca')
        if cached.get('config') == config and getattr(cached_pca, 'fit_method', None) == 'streaming_covariance':
            print(f'Reusing pre-wavelet covariance PCA: {checkpoint_path}')
            return cached
        print('Found pre-wavelet PCA checkpoint, but config/method changed; refitting.')

    availability_rows = []
    n_features = None
    for index, global_id in enumerate(global_ids, start=1):
        species, individual_id = parse_global_id(global_id)
        bundle = base_loader(species, individual_id=individual_id, dataset_name=REPRESENTATION_NAME)
        if n_features is None:
            n_features = int(bundle['X'].shape[1])
        elif bundle['X'].shape[1] != n_features:
            raise ValueError(
                f'{global_id}: expected {n_features} features, got {bundle["X"].shape[1]}'
            )
        availability_rows.append({
            'global_id': global_id,
            'species': species,
            'individual_id': individual_id,
            'n_raw_frames': int(bundle['X'].shape[0]),
            'available_sample_rows': _available_fixed_stride_rows(
                bundle['X'].shape[0], DISTANCE_PCA_SUBSAMPLE_FACTOR
            ),
            'n_features': int(bundle['X'].shape[1]),
        })
        print(f'[{index}/{len(global_ids)}] distance PCA availability {global_id}: {availability_rows[-1]["available_sample_rows"]:,} rows')
        del bundle
        gc.collect()

    if BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES:
        sample_plan = _build_species_balanced_distance_pca_plan(
            availability_rows,
            rows_per_species=DISTANCE_PCA_ROWS_PER_SPECIES,
        )
    else:
        sample_plan = pd.DataFrame(availability_rows).copy()
        sample_plan['species_sample_budget'] = sample_plan.groupby('species')['available_sample_rows'].transform('sum')
        sample_plan['n_sample_rows'] = sample_plan['available_sample_rows']

    sample_plan.to_csv(balanced_plan_path, index=False)
    species_plan = sample_plan.groupby('species')[['available_sample_rows', 'n_sample_rows']].sum().reset_index()
    print('pre-wavelet covariance PCA sample rows by species:')
    display(species_plan)

    n_fit_components = min(
        int(DISTANCE_PCA_MAX_COMPONENTS),
        int(n_features),
        int(sample_plan['n_sample_rows'].sum()),
    )
    print(f'pre-wavelet covariance PCA: {n_fit_components} components from {n_features} features')
    pca = pup.fit_streaming_covariance_pca(
        _iter_distance_pca_batches(sample_plan, seed=SEED),
        n_components=n_fit_components,
        verbose=True,
        label='pre-wavelet PCA',
    )

    cumulative = np.cumsum(np.asarray(pca.explained_variance_ratio_, dtype=float))
    idx = int(np.searchsorted(cumulative, DISTANCE_PCA_VARIANCE_TARGET, side='left'))
    reached = idx < len(cumulative)
    n_kept = idx + 1 if reached else len(cumulative)
    result = {
        'config': config,
        'pca': pca,
        'n_components': int(n_kept),
        'fit_components': int(pca.n_components_),
        'explained_variance': pca.explained_variance_,
        'explained_variance_ratio': pca.explained_variance_ratio_,
        'cumulative_variance': cumulative,
        'variance_target': float(DISTANCE_PCA_VARIANCE_TARGET),
        'variance_target_reached': bool(reached),
        'sample_shape': (int(sample_plan['n_sample_rows'].sum()), int(n_features)),
        'pca_fit_method': getattr(pca, 'fit_method', DISTANCE_PCA_FIT_METHOD),
        'pca_fit_rows': int(sample_plan['n_sample_rows'].sum()),
        'sample_rows': sample_plan,
        'balance_samples_by_species': bool(BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES),
        'rows_per_species': (
            None if DISTANCE_PCA_ROWS_PER_SPECIES is None else int(DISTANCE_PCA_ROWS_PER_SPECIES)
        ),
        'output_file': str(checkpoint_path),
    }
    with open(checkpoint_path, 'wb') as handle:
        pickle.dump(result, handle)
    sample_plan.to_csv(sample_manifest_path, index=False)
    print(f'Saved pre-wavelet covariance PCA: {checkpoint_path}')
    print(f'Covariance PCA saw {result["pca_fit_rows"]:,} sampled rows total')
    gc.collect()
    return result


distance_pca_result = fit_or_load_distance_pca()
pre_wavelet_pca = distance_pca_result['pca']
pre_wavelet_n_components = int(distance_pca_result['n_components'])
print(f'keeping {pre_wavelet_n_components} pre-wavelet PCs')

[1/354] distance PCA availability Mus_caroli__subject__CAROLI-F-2L-741: 8,641 rows
[2/354] distance PCA availability Mus_caroli__subject__CAROLI-F-L-737: 12,961 rows
[3/354] distance PCA availability Mus_caroli__subject__CAROLI-F-L-741: 12,961 rows
[4/354] distance PCA availability Mus_caroli__subject__CAROLI-F-LR-741: 12,961 rows
[5/354] distance PCA availability Mus_caroli__subject__CAROLI-F-N-740: 12,961 rows
[6/354] distance PCA availability Mus_caroli__subject__CAROLI-F-N-741: 12,961 rows
[7/354] distance PCA availability Mus_caroli__subject__CAROLI-F-R-737: 12,961 rows
[8/354] distance PCA availability Mus_caroli__subject__CAROLI-F-R-741: 12,961 rows
[9/354] distance PCA availability Mus_caroli__subject__CAROLI-M-L-734: 12,961 rows
[10/354] distance PCA availability Mus_caroli__subject__CAROLI-M-L-735: 12,961 rows
[11/354] distance PCA availability Mus_caroli__subject__CAROLI-M-L-738: 12,961 rows
[12/354] distance PCA availability Mus_caroli__subject__CAROLI-M-LR-734: 8,641 rows
[13/354] distance PCA availability Mus_caroli__subject__CAROLI-M-N-739: 12,961 rows
[14/354] distance PCA availability Mus_caroli__subject__CAROLI-M-R-734: 12,961 rows
[15/354] distance PCA availability Mus_caroli__subject__CAROLI-M-R-738: 12,961 rows
[16/354] distance PCA availability Mus_musculus__subject__40256.0: 12,960 rows
[17/354] distance PCA availability Mus_musculus__subject__40257.0: 12,960 rows
[18/354] distance PCA availability Mus_musculus__subject__40258.0: 8,640 rows
[19/354] distance PCA availability Mus_musculus__subject__40259.0: 8,640 rows
[20/354] distance PCA availability Mus_musculus__subject__40260.0: 8,640 rows
[21/354] distance PCA availability Mus_musculus__subject__40261.0: 12,960 rows
[22/354] distance PCA availability Mus_musculus__subject__40262.0: 12,960 rows
[23/354] distance PCA availability Mus_musculus__subject__40263.0: 8,640 rows
[24/354] distance PCA availability Mus_musculus__subject__40264.0: 12,960 rows
[25/354] distance PCA availability Mus_musculus__subject__40265.0: 4,320 rows
[26/354] distance PCA availability Mus_musculus__subject__40266.0: 12,960 rows
[27/354] distance PCA availability Mus_musculus__subject__40267.0: 12,960 rows
[28/354] distance PCA availability Mus_musculus__subject__40268.0: 12,960 rows
[29/354] distance PCA availability Mus_musculus__subject__40269.0: 12,960 rows
[30/354] distance PCA availability Mus_musculus__subject__40270.0: 8,640 rows
[31/354] distance PCA availability Mus_musculus__subject__40271.0: 12,960 rows
[32/354] distance PCA availability Mus_musculus__subject__CAST-F-L-CM1: 30,242 rows
[33/354] distance PCA availability Mus_musculus__subject__CAST-F-L-CM2: 30,242 rows
[34/354] distance PCA availability Mus_musculus__subject__CAST-F-LR-CM1: 34,562 rows
[35/354] distance PCA availability Mus_musculus__subject__CAST-F-LR-CM2: 34,562 rows
[36/354] distance PCA availability Mus_musculus__subject__CAST-F-N-CM1: 34,562 rows
[37/354] distance PCA availability Mus_musculus__subject__CAST-F-N-CM2: 30,242 rows
[38/354] distance PCA availability Mus_musculus__subject__CAST-F-R-CM1: 34,562 rows
[39/354] distance PCA availability Mus_musculus__subject__CAST-F-R-CM2: 34,562 rows
[40/354] distance PCA availability Mus_musculus__subject__CAST-M-L-CM3: 34,562 rows
[41/354] distance PCA availability Mus_musculus__subject__CAST-M-L-CM4: 21,601 rows
[42/354] distance PCA availability Mus_musculus__subject__CAST-M-LR-CM3: 34,562 rows
[43/354] distance PCA availability Mus_musculus__subject__CAST-M-LR-CM4: 30,242 rows
[44/354] distance PCA availability Mus_musculus__subject__CAST-M-N-CM3: 34,562 rows
[45/354] distance PCA availability Mus_musculus__subject__CAST-M-N-CM4: 30,242 rows
[46/354] distance PCA availability Mus_musculus__subject__CAST-M-R-CM3: 30,242 rows
[47/354] distance PCA availability Mus_musculus__subject__CAST-M-R-CM4: 30,242 rows
[48/354] distance PCA availability Mus_musculus__subject__DO-F-L-143: 12,961 rows
[49/354] distance PCA availability Mus_musculus__subject__DO-F-L-144: 12,961 rows
[50/354] distance PCA availability Mus_musculus__subject__DO-F-LR-143: 12,961 rows
[51/354] distance PCA availability Mus_musculus__subject__DO-F-LR-144: 12,961 rows
[52/354] distance PCA availability Mus_musculus__subject__DO-F-N-143: 12,961 rows
[53/354] distance PCA availability Mus_musculus__subject__DO-F-N-144: 12,961 rows
[54/354] distance PCA availability Mus_musculus__subject__DO-F-R-143: 12,961 rows
[55/354] distance PCA availability Mus_musculus__subject__DO-F-R-144: 12,961 rows
[56/354] distance PCA availability Mus_musculus__subject__DO-M-2L-142: 12,961 rows
[57/354] distance PCA availability Mus_musculus__subject__DO-M-2R-142: 12,961 rows
[58/354] distance PCA availability Mus_musculus__subject__DO-M-L-141: 12,961 rows
[59/354] distance PCA availability Mus_musculus__subject__DO-M-L-142: 12,961 rows
[60/354] distance PCA availability Mus_musculus__subject__DO-M-LR-141: 12,961 rows
[61/354] distance PCA availability Mus_musculus__subject__DO-M-R-141: 8,641 rows
[62/354] distance PCA availability Mus_musculus__subject__DO-M-R-142: 12,961 rows
[63/354] distance PCA availability Mus_musculus__subject__F1-F-L-159: 8,641 rows
[64/354] distance PCA availability Mus_musculus__subject__F1-F-R-159: 12,961 rows
[65/354] distance PCA availability Mus_musculus__subject__F1-M-L-166: 8,641 rows
[66/354] distance PCA availability Mus_musculus__subject__F1-M-R-166: 8,641 rows
[67/354] distance PCA availability Mus_musculus__subject__MOLF-F-2L-133: 25,921 rows
[68/354] distance PCA availability Mus_musculus__subject__MOLF-F-L-131: 21,601 rows
[69/354] distance PCA availability Mus_musculus__subject__MOLF-F-L-133: 25,921 rows
[70/354] distance PCA availability Mus_musculus__subject__MOLF-F-LR-133: 34,562 rows
[71/354] distance PCA availability Mus_musculus__subject__MOLF-F-N-133: 25,921 rows
[72/354] distance PCA availability Mus_musculus__subject__MOLF-F-R-131: 25,921 rows
[73/354] distance PCA availability Mus_musculus__subject__MOLF-F-R-133: 25,921 rows
[74/354] distance PCA availability Mus_musculus__subject__MOLF-M-L-132: 30,242 rows
[75/354] distance PCA availability Mus_musculus__subject__MOLF-M-LR-132: 4,321 rows
[76/354] distance PCA availability Mus_musculus__subject__MOLF-M-N-132: 34,562 rows
[77/354] distance PCA availability Mus_musculus__subject__MOLF-M-R-132: 30,242 rows
[78/354] distance PCA availability Mus_musculus__subject__PWK-F-L-833: 25,921 rows
[79/354] distance PCA availability Mus_musculus__subject__PWK-F-L-834: 25,921 rows
[80/354] distance PCA availability Mus_musculus__subject__PWK-F-LR-833: 25,921 rows
[81/354] distance PCA availability Mus_musculus__subject__PWK-F-LR-834: 25,921 rows
[82/354] distance PCA availability Mus_musculus__subject__PWK-F-N-833: 25,921 rows
[83/354] distance PCA availability Mus_musculus__subject__PWK-F-N-834: 25,921 rows
[84/354] distance PCA availability Mus_musculus__subject__PWK-F-R-833: 21,601 rows
[85/354] distance PCA availability Mus_musculus__subject__PWK-F-R-834: 25,921 rows
[86/354] distance PCA availability Mus_musculus__subject__PWK-M-L-831: 25,921 rows
[87/354] distance PCA availability Mus_musculus__subject__PWK-M-L-832: 25,921 rows
[88/354] distance PCA availability Mus_musculus__subject__PWK-M-LR-831: 25,921 rows
[89/354] distance PCA availability Mus_musculus__subject__PWK-M-LR-832: 17,281 rows
[90/354] distance PCA availability Mus_musculus__subject__PWK-M-N-831: 25,921 rows
[91/354] distance PCA availability Mus_musculus__subject__PWK-M-N-832: 25,921 rows
[92/354] distance PCA availability Mus_musculus__subject__PWK-M-R-831: 25,921 rows
[93/354] distance PCA availability Mus_musculus__subject__PWK-M-R-832: 25,921 rows
[94/354] distance PCA availability Mus_musculus__subject__WSB-F-L-235: 4,321 rows
[95/354] distance PCA availability Mus_musculus__subject__WSB-F-L-236: 4,321 rows
[96/354] distance PCA availability Mus_musculus__subject__WSB-F-LR-235: 8,641 rows
[97/354] distance PCA availability Mus_musculus__subject__WSB-F-LR-236: 8,641 rows
[98/354] distance PCA availability Mus_musculus__subject__WSB-F-N-235: 8,641 rows
[99/354] distance PCA availability Mus_musculus__subject__WSB-F-R-235: 4,321 rows
[100/354] distance PCA availability Mus_musculus__subject__WSB-F-R-236: 4,321 rows
[101/354] distance PCA availability Mus_musculus__subject__WSB-M-2L-234: 8,641 rows
[102/354] distance PCA availability Mus_musculus__subject__WSB-M-L-233: 8,641 rows
[103/354] distance PCA availability Mus_musculus__subject__WSB-M-L-234: 8,641 rows
[104/354] distance PCA availability Mus_musculus__subject__WSB-M-LR-233: 8,641 rows
[105/354] distance PCA availability Mus_musculus__subject__WSB-M-LR-234: 8,641 rows
[106/354] distance PCA availability Mus_musculus__subject__WSB-M-N-234: 8,641 rows
[107/354] distance PCA availability Mus_musculus__subject__WSB-M-R-233: 8,641 rows
[108/354] distance PCA availability Mus_musculus__subject__WSB-M-R-234: 8,641 rows
[109/354] distance PCA availability Mus_spretus__subject__SPRET-F-L-730: 12,961 rows
[110/354] distance PCA availability Mus_spretus__subject__SPRET-F-L-732: 12,961 rows
[111/354] distance PCA availability Mus_spretus__subject__SPRET-F-L-742: 12,961 rows
[112/354] distance PCA availability Mus_spretus__subject__SPRET-F-LR-730: 12,961 rows
[113/354] distance PCA availability Mus_spretus__subject__SPRET-F-N-731: 8,641 rows
[114/354] distance PCA availability Mus_spretus__subject__SPRET-F-N-744: 12,961 rows
[115/354] distance PCA availability Mus_spretus__subject__SPRET-F-N-745: 12,961 rows
[116/354] distance PCA availability Mus_spretus__subject__SPRET-F-R-730: 12,961 rows
[117/354] distance PCA availability Mus_spretus__subject__SPRET-F-R-732: 12,961 rows
[118/354] distance PCA availability Mus_spretus__subject__SPRET-F-R-742: 8,641 rows
[119/354] distance PCA availability Mus_spretus__subject__SPRET-F-R-743: 8,641 rows
[120/354] distance PCA availability Mus_spretus__subject__SPRET-M-L-728: 12,961 rows
[121/354] distance PCA availability Mus_spretus__subject__SPRET-M-L-729: 12,961 rows
[122/354] distance PCA availability Mus_spretus__subject__SPRET-M-L-733: 12,961 rows
[123/354] distance PCA availability Mus_spretus__subject__SPRET-M-R-729: 12,961 rows
[124/354] distance PCA availability Mus_spretus__subject__SPRET-M-R-733: 12,961 rows
[125/354] distance PCA availability Peromyscus_californicus__subject__38824.0: 4,320 rows
[126/354] distance PCA availability Peromyscus_californicus__subject__38825.0: 4,320 rows
[127/354] distance PCA availability Peromyscus_californicus__subject__38826.0: 8,640 rows
[128/354] distance PCA availability Peromyscus_californicus__subject__38827.0: 4,320 rows
[129/354] distance PCA availability Peromyscus_californicus__subject__39356.0: 4,320 rows
[130/354] distance PCA availability Peromyscus_californicus__subject__39357.0: 4,320 rows
[131/354] distance PCA availability Peromyscus_californicus__subject__39358.0: 4,320 rows
[132/354] distance PCA availability Peromyscus_californicus__subject__39359.0: 4,320 rows
[133/354] distance PCA availability Peromyscus_californicus__subject__39360.0: 4,320 rows
[134/354] distance PCA availability Peromyscus_californicus__subject__40227.0: 4,320 rows
[135/354] distance PCA availability Peromyscus_californicus__subject__40407.0: 4,320 rows
[136/354] distance PCA availability Peromyscus_californicus__subject__40447.0: 4,320 rows
[137/354] distance PCA availability Peromyscus_californicus__subject__40594.0: 4,320 rows
[138/354] distance PCA availability Peromyscus_californicus__subject__40595.0: 4,320 rows
[139/354] distance PCA availability Peromyscus_californicus__subject__40663.0: 4,320 rows
[140/354] distance PCA availability Peromyscus_californicus__subject__40664.0: 4,320 rows
[141/354] distance PCA availability Peromyscus_californicus__subject__40774.0: 4,320 rows
[142/354] distance PCA availability Peromyscus_californicus__subject__40775.0: 4,320 rows
[143/354] distance PCA availability Peromyscus_californicus__subject__40880.0: 4,320 rows
[144/354] distance PCA availability Peromyscus_californicus__subject__40881.0: 4,320 rows
[145/354] distance PCA availability Peromyscus_californicus__subject__40882.0: 4,320 rows
[146/354] distance PCA availability Peromyscus_californicus__subject__41042.0: 4,320 rows
[147/354] distance PCA availability Peromyscus_californicus__subject__41043.0: 4,320 rows
[148/354] distance PCA availability Peromyscus_gossypinus__subject__37988.0: 4,320 rows
[149/354] distance PCA availability Peromyscus_gossypinus__subject__37989.0: 4,320 rows
[150/354] distance PCA availability Peromyscus_gossypinus__subject__37990.0: 4,320 rows
[151/354] distance PCA availability Peromyscus_gossypinus__subject__38033.0: 4,320 rows
[152/354] distance PCA availability Peromyscus_gossypinus__subject__38291.0: 4,320 rows
[153/354] distance PCA availability Peromyscus_gossypinus__subject__38305.0: 4,320 rows
[154/354] distance PCA availability Peromyscus_gossypinus__subject__38983.0: 4,320 rows
[155/354] distance PCA availability Peromyscus_gossypinus__subject__38984.0: 4,320 rows
[156/354] distance PCA availability Peromyscus_gossypinus__subject__38985.0: 4,320 rows
[157/354] distance PCA availability Peromyscus_gossypinus__subject__38989.0: 4,320 rows
[158/354] distance PCA availability Peromyscus_gossypinus__subject__38990.0: 4,320 rows
[159/354] distance PCA availability Peromyscus_gossypinus__subject__38991.0: 4,320 rows
[160/354] distance PCA availability Peromyscus_gossypinus__subject__38992.0: 4,320 rows
[161/354] distance PCA availability Peromyscus_gossypinus__subject__38993.0: 4,320 rows
[162/354] distance PCA availability Peromyscus_gossypinus__subject__39060.0: 4,320 rows
[163/354] distance PCA availability Peromyscus_gossypinus__subject__39231.0: 4,320 rows
[164/354] distance PCA availability Peromyscus_gossypinus__subject__39232.0: 4,320 rows
[165/354] distance PCA availability Peromyscus_gossypinus__subject__39233.0: 4,320 rows
[166/354] distance PCA availability Peromyscus_gossypinus__subject__39265.0: 4,320 rows
[167/354] distance PCA availability Peromyscus_gossypinus__subject__39266.0: 4,320 rows
[168/354] distance PCA availability Peromyscus_leucopus__subject__37991.0: 4,320 rows
[169/354] distance PCA availability Peromyscus_leucopus__subject__37992.0: 4,320 rows
[170/354] distance PCA availability Peromyscus_leucopus__subject__38207.0: 4,320 rows
[171/354] distance PCA availability Peromyscus_leucopus__subject__38296.0: 4,320 rows
[172/354] distance PCA availability Peromyscus_leucopus__subject__38297.0: 4,320 rows
[173/354] distance PCA availability Peromyscus_leucopus__subject__39026.0: 4,320 rows
[174/354] distance PCA availability Peromyscus_leucopus__subject__39787.0: 4,320 rows
[175/354] distance PCA availability Peromyscus_leucopus__subject__39788.0: 4,320 rows
[176/354] distance PCA availability Peromyscus_leucopus__subject__39811.0: 4,320 rows
[177/354] distance PCA availability Peromyscus_leucopus__subject__39812.0: 4,320 rows
[178/354] distance PCA availability Peromyscus_leucopus__subject__39883.0: 4,320 rows
[179/354] distance PCA availability Peromyscus_leucopus__subject__40923.0: 4,320 rows
[180/354] distance PCA availability Peromyscus_leucopus__subject__40926.0: 4,320 rows
[181/354] distance PCA availability Peromyscus_leucopus__subject__40927.0: 4,320 rows
[182/354] distance PCA availability Peromyscus_maniculatus__subject__28247.0: 4,320 rows
[183/354] distance PCA availability Peromyscus_maniculatus__subject__28529.0: 4,320 rows
[184/354] distance PCA availability Peromyscus_maniculatus__subject__34456.0: 4,320 rows
[185/354] distance PCA availability Peromyscus_maniculatus__subject__34457.0: 4,320 rows
[186/354] distance PCA availability Peromyscus_maniculatus__subject__34459.0: 4,320 rows
[187/354] distance PCA availability Peromyscus_maniculatus__subject__37837.0: 4,320 rows
[188/354] distance PCA availability Peromyscus_maniculatus__subject__37838.0: 4,320 rows
[189/354] distance PCA availability Peromyscus_maniculatus__subject__37839.0: 4,320 rows
[190/354] distance PCA availability Peromyscus_maniculatus__subject__37950.0: 4,320 rows
[191/354] distance PCA availability Peromyscus_maniculatus__subject__37951.0: 4,320 rows
[192/354] distance PCA availability Peromyscus_maniculatus__subject__37953.0: 4,320 rows
[193/354] distance PCA availability Peromyscus_maniculatus__subject__37954.0: 4,320 rows
[194/354] distance PCA availability Peromyscus_maniculatus__subject__37955.0: 4,320 rows
[195/354] distance PCA availability Peromyscus_maniculatus__subject__37956.0: 4,320 rows
[196/354] distance PCA availability Peromyscus_maniculatus__subject__38027.0: 4,320 rows
[197/354] distance PCA availability Peromyscus_maniculatus__subject__38028.0: 4,320 rows
[198/354] distance PCA availability Peromyscus_maniculatus__subject__38029.0: 4,320 rows
[199/354] distance PCA availability Peromyscus_maniculatus__subject__38069.0: 4,320 rows
[200/354] distance PCA availability Peromyscus_maniculatus__subject__38070.0: 4,320 rows
[201/354] distance PCA availability Peromyscus_maniculatus__subject__38102.0: 8,640 rows
[202/354] distance PCA availability Peromyscus_maniculatus__subject__38103.0: 4,320 rows
[203/354] distance PCA availability Peromyscus_maniculatus__subject__38104.0: 4,320 rows
[204/354] distance PCA availability Peromyscus_maniculatus__subject__38105.0: 4,320 rows
[205/354] distance PCA availability Peromyscus_maniculatus__subject__38110.0: 8,640 rows
[206/354] distance PCA availability Peromyscus_maniculatus__subject__38111.0: 8,640 rows
[207/354] distance PCA availability Peromyscus_maniculatus__subject__38112.0: 8,640 rows
[208/354] distance PCA availability Peromyscus_maniculatus__subject__38124.0: 4,320 rows
[209/354] distance PCA availability Peromyscus_maniculatus__subject__38125.0: 4,320 rows
[210/354] distance PCA availability Peromyscus_maniculatus__subject__38126.0: 4,320 rows
[211/354] distance PCA availability Peromyscus_maniculatus__subject__38127.0: 4,320 rows
[212/354] distance PCA availability Peromyscus_maniculatus__subject__38128.0: 4,320 rows
[213/354] distance PCA availability Peromyscus_maniculatus__subject__38129.0: 4,320 rows
[214/354] distance PCA availability Peromyscus_maniculatus__subject__38130.0: 4,320 rows
[215/354] distance PCA availability Peromyscus_maniculatus__subject__38154.0: 8,640 rows
[216/354] distance PCA availability Peromyscus_maniculatus__subject__38155.0: 8,640 rows
[217/354] distance PCA availability Peromyscus_maniculatus__subject__38156.0: 4,320 rows
[218/354] distance PCA availability Peromyscus_maniculatus__subject__38157.0: 4,320 rows
[219/354] distance PCA availability Peromyscus_maniculatus__subject__38158.0: 4,320 rows
[220/354] distance PCA availability Peromyscus_maniculatus__subject__38159.0: 4,320 rows
[221/354] distance PCA availability Peromyscus_maniculatus__subject__38196.0: 4,320 rows
[222/354] distance PCA availability Peromyscus_maniculatus__subject__38197.0: 4,320 rows
[223/354] distance PCA availability Peromyscus_maniculatus__subject__38198.0: 4,320 rows
[224/354] distance PCA availability Peromyscus_maniculatus__subject__38199.0: 4,320 rows
[225/354] distance PCA availability Peromyscus_maniculatus__subject__38200.0: 4,320 rows
[226/354] distance PCA availability Peromyscus_maniculatus__subject__38201.0: 4,320 rows
[227/354] distance PCA availability Peromyscus_maniculatus__subject__38208.0: 4,320 rows
[228/354] distance PCA availability Peromyscus_maniculatus__subject__38209.0: 4,320 rows
[229/354] distance PCA availability Peromyscus_maniculatus__subject__38235.0: 4,320 rows
[230/354] distance PCA availability Peromyscus_maniculatus__subject__38246.0: 4,320 rows
[231/354] distance PCA availability Peromyscus_maniculatus__subject__38285.0: 4,320 rows
[232/354] distance PCA availability Peromyscus_maniculatus__subject__38286.0: 4,320 rows
[233/354] distance PCA availability Peromyscus_maniculatus__subject__38298.0: 4,320 rows

                   species  available_sample_rows  n_sample_rows
0               Mus_caroli                 185775          60480
1             Mus_musculus                1715136          60480
2              Mus_spretus                 194416          60480
3  Peromyscus_californicus                 103680          60480
4    Peromyscus_gossypinus                  86400          60480
5      Peromyscus_leucopus                  60480          60480
6   Peromyscus_maniculatus                 635040          60480
7    Peromyscus_polionotus                 211680          60480

pre-wavelet covariance PCA: 100 components from 300 features
[1/354] covariance sample Mus_caroli__subject__CAROLI-F-2L-741: (2813, 300)
    covariance batch 1: (2813, 300), rows seen=2,813
[2/354] covariance sample Mus_caroli__subject__CAROLI-F-L-737: (4220, 300)
    covariance batch 2: (4220, 300), rows seen=7,033
[3/354] covariance sample Mus_caroli__subject__CAROLI-F-L-741: (4220, 300)
    covariance batch 3: (4220, 300), rows seen=11,253
[4/354] covariance sample Mus_caroli__subject__CAROLI-F-LR-741: (4220, 300)
    covariance batch 4: (4220, 300), rows seen=15,473
[5/354] covariance sample Mus_caroli__subject__CAROLI-F-N-740: (4220, 300)
    covariance batch 5: (4220, 300), rows seen=19,693
[6/354] covariance sample Mus_caroli__subject__CAROLI-F-N-741: (4220, 300)
    covariance batch 6: (4220, 300), rows seen=23,913
[7/354] covariance sample Mus_caroli__subject__CAROLI-F-R-737: (4220, 300)
    covariance batch 7: (4220, 300), rows seen=28,133
[8/354] covariance sample Mus_caroli__subject__CAROLI-F-R-741: (4220, 300)
    covariance batch 8: (4220, 300), rows seen=32,353
[9/354] covariance sample Mus_caroli__subject__CAROLI-M-L-734: (4219, 300)
    covariance batch 9: (4219, 300), rows seen=36,572
[10/354] covariance sample Mus_caroli__subject__CAROLI-M-L-735: (4219, 300)
    covariance batch 10: (4219, 300), rows seen=40,791
[11/354] covariance sample Mus_caroli__subject__CAROLI-M-L-738: (4219, 300)
    covariance batch 11: (4219, 300), rows seen=45,010
[12/354] covariance sample Mus_caroli__subject__CAROLI-M-LR-734: (2813, 300)
    covariance batch 12: (2813, 300), rows seen=47,823
[13/354] covariance sample Mus_caroli__subject__CAROLI-M-N-739: (4219, 300)
    covariance batch 13: (4219, 300), rows seen=52,042
[14/354] covariance sample Mus_caroli__subject__CAROLI-M-R-734: (4219, 300)
    covariance batch 14: (4219, 300), rows seen=56,261
[15/354] covariance sample Mus_caroli__subject__CAROLI-M-R-738: (4219, 300)
    covariance batch 15: (4219, 300), rows seen=60,480
[16/354] covariance sample Mus_musculus__subject__40256.0: (457, 300)
    covariance batch 16: (457, 300), rows seen=60,937
[17/354] covariance sample Mus_musculus__subject__40257.0: (457, 300)
    covariance batch 17: (457, 300), rows seen=61,394
[18/354] covariance sample Mus_musculus__subject__40258.0: (305, 300)
    covariance batch 18: (305, 300), rows seen=61,699
[19/354] covariance sample Mus_musculus__subject__40259.0: (305, 300)
    covariance batch 19: (305, 300), rows seen=62,004
[20/354] covariance sample Mus_musculus__subject__40260.0: (305, 300)
    covariance batch 20: (305, 300), rows seen=62,309
[21/354] covariance sample Mus_musculus__subject__40261.0: (457, 300)
    covariance batch 21: (457, 300), rows seen=62,766
[22/354] covariance sample Mus_musculus__subject__40262.0: (457, 300)
    covariance batch 22: (457, 300), rows seen=63,223
[23/354] covariance sample Mus_musculus__subject__40263.0: (304, 300)
    covariance batch 23: (304, 300), rows seen=63,527
[24/354] covariance sample Mus_musculus__subject__40264.0: (457, 300)
    covariance batch 24: (457, 300), rows seen=63,984
[25/354] covariance sample Mus_musculus__subject__40265.0: (152, 300)
    covariance batch 25: (152, 300), rows seen=64,136
[26/354] covariance sample Mus_musculus__subject__40266.0: (457, 300)
    covariance batch 26: (457, 300), rows seen=64,593
[27/354] covariance sample Mus_musculus__subject__40267.0: (457, 300)
    covariance batch 27: (457, 300), rows seen=65,050
[28/354] covariance sample Mus_musculus__subject__40268.0: (457, 300)
    covariance batch 28: (457, 300), rows seen=65,507
[29/354] covariance sample Mus_musculus__subject__40269.0: (457, 300)
    covariance batch 29: (457, 300), rows seen=65,964
[30/354] covariance sample Mus_musculus__subject__40270.0: (304, 300)
    covariance batch 30: (304, 300), rows seen=66,268
[31/354] covariance sample Mus_musculus__subject__40271.0: (457, 300)
    covariance batch 31: (457, 300), rows seen=66,725
[32/354] covariance sample Mus_musculus__subject__CAST-F-L-CM1: (1066, 300)
    covariance batch 32: (1066, 300), rows seen=67,791
[33/354] covariance sample Mus_musculus__subject__CAST-F-L-CM2: (1066, 300)
    covariance batch 33: (1066, 300), rows seen=68,857
[34/354] covariance sample Mus_musculus__subject__CAST-F-LR-CM1: (1219, 300)
    covariance batch 34: (1219, 300), rows seen=70,076
[35/354] covariance sample Mus_musculus__subject__CAST-F-LR-CM2: (1219, 300)
    covariance batch 35: (1219, 300), rows seen=71,295
[36/354] covariance sample Mus_musculus__subject__CAST-F-N-CM1: (1219, 300)
    covariance batch 36: (1219, 300), rows seen=72,514
[37/354] covariance sample Mus_musculus__subject__CAST-F-N-CM2: (1066, 300)
    covariance batch 37: (1066, 300), rows seen=73,580
[38/354] covariance sample Mus_musculus__subject__CAST-F-R-CM1: (1219, 300)
    covariance batch 38: (1219, 300), rows seen=74,799
[39/354] covariance sample Mus_musculus__subject__CAST-F-R-CM2: (1219, 300)
    covariance batch 39: (1219, 300), rows seen=76,018
[40/354] covariance sample Mus_musculus__subject__CAST-M-L-CM3: (1219, 300)
    covariance batch 40: (1219, 300), rows seen=77,237
[41/354] covariance sample Mus_musculus__subject__CAST-M-L-CM4: (762, 300)
    covariance batch 41: (762, 300), rows seen=77,999
[42/354] covariance sample Mus_musculus__subject__CAST-M-LR-CM3: (1219, 300)
    covariance batch 42: (1219, 300), rows seen=79,218
[43/354] covariance sample Mus_musculus__subject__CAST-M-LR-CM4: (1066, 300)
    covariance batch 43: (1066, 300), rows seen=80,284
[44/354] covariance sample Mus_musculus__subject__CAST-M-N-CM3: (1219, 300)
    covariance batch 44: (1219, 300), rows seen=81,503
[45/354] covariance sample Mus_musculus__subject__CAST-M-N-CM4: (1066, 300)
    covariance batch 45: (1066, 300), rows seen=82,569
[46/354] covariance sample Mus_musculus__subject__CAST-M-R-CM3: (1066, 300)
    covariance batch 46: (1066, 300), rows seen=83,635
[47/354] covariance sample Mus_musculus__subject__CAST-M-R-CM4: (1066, 300)
    covariance batch 47: (1066, 300), rows seen=84,701
[48/354] covariance sample Mus_musculus__subject__DO-F-L-143: (457, 300)
    covariance batch 48: (457, 300), rows seen=85,158
[49/354] covariance sample Mus_musculus__subject__DO-F-L-144: (457, 300)
    covariance batch 49: (457, 300), rows seen=85,615
[50/354] covariance sample Mus_musculus__subject__DO-F-LR-143: (457, 300)
    covariance batch 50: (457, 300), rows seen=86,072
[51/354] covariance sample Mus_musculus__subject__DO-F-LR-144: (457, 300)
    covariance batch 51: (457, 300), rows seen=86,529
[52/354] covariance sample Mus_musculus__subject__DO-F-N-143: (457, 300)
    covariance batch 52: (457, 300), rows seen=86,986
[53/354] covariance sample Mus_musculus__subject__DO-F-N-144: (457, 300)
    covariance batch 53: (457, 300), rows seen=87,443
[54/354] covariance sample Mus_musculus__subject__DO-F-R-143: (457, 300)
    covariance batch 54: (457, 300), rows seen=87,900
[55/354] covariance sample Mus_musculus__subject__DO-F-R-144: (457, 300)
    covariance batch 55: (457, 300), rows seen=88,357
[56/354] covariance sample Mus_musculus__subject__DO-M-2L-142: (457, 300)
    covariance batch 56: (457, 300), rows seen=88,814
[57/354] covariance sample Mus_musculus__subject__DO-M-2R-142: (457, 300)
    covariance batch 57: (457, 300), rows seen=89,271
[58/354] covariance sample Mus_musculus__subject__DO-M-L-141: (457, 300)
    covariance batch 58: (457, 300), rows seen=89,728
[59/354] covariance sample Mus_musculus__subject__DO-M-L-142: (457, 300)
    covariance batch 59: (457, 300), rows seen=90,185
[60/354] covariance sample Mus_musculus__subject__DO-M-LR-141: (457, 300)
    covariance batch 60: (457, 300), rows seen=90,642
[61/354] covariance sample Mus_musculus__subject__DO-M-R-141: (305, 300)
    covariance batch 61: (305, 300), rows seen=90,947
[62/354] covariance sample Mus_musculus__subject__DO-M-R-142: (457, 300)
    covariance batch 62: (457, 300), rows seen=91,404
[63/354] covariance sample Mus_musculus__subject__F1-F-L-159: (305, 300)
    covariance batch 63: (305, 300), rows seen=91,709
[64/354] covariance sample Mus_musculus__subject__F1-F-R-159: (457, 300)
    covariance batch 64: (457, 300), rows seen=92,166
[65/354] covariance sample Mus_musculus__subject__F1-M-L-166: (305, 300)
    covariance batch 65: (305, 300), rows seen=92,471
[66/354] covariance sample Mus_musculus__subject__F1-M-R-166: (305, 300)
    covariance batch 66: (305, 300), rows seen=92,776
[67/354] covariance sample Mus_musculus__subject__MOLF-F-2L-133: (914, 300)
    covariance batch 67: (914, 300), rows seen=93,690
[68/354] covariance sample Mus_musculus__subject__MOLF-F-L-131: (762, 300)
    covariance batch 68: (762, 300), rows seen=94,452
[69/354] covariance sample Mus_musculus__subject__MOLF-F-L-133: (914, 300)
    covariance batch 69: (914, 300), rows seen=95,366
[70/354] covariance sample Mus_musculus__subject__MOLF-F-LR-133: (1219, 300)
    covariance batch 70: (1219, 300), rows seen=96,585
[71/354] covariance sample Mus_musculus__subject__MOLF-F-N-133: (914, 300)
    covariance batch 71: (914, 300), rows seen=97,499
[72/354] covariance sample Mus_musculus__subject__MOLF-F-R-131: (914, 300)
    covariance batch 72: (914, 300), rows seen=98,413
[73/354] covariance sample Mus_musculus__subject__MOLF-F-R-133: (914, 300)
    covariance batch 73: (914, 300), rows seen=99,327
[74/354] covariance sample Mus_musculus__subject__MOLF-M-L-132: (1066, 300)
    covariance batch 74: (1066, 300), rows seen=100,393
[75/354] covariance sample Mus_musculus__subject__MOLF-M-LR-132: (152, 300)
    covariance batch 75: (152, 300), rows seen=100,545
[76/354] covariance sample Mus_musculus__subject__MOLF-M-N-132: (1219, 300)
    covariance batch 76: (1219, 300), rows seen=101,764
[77/354] covariance sample Mus_musculus__subject__MOLF-M-R-132: (1066, 300)
    covariance batch 77: (1066, 300), rows seen=102,830
[78/354] covariance sample Mus_musculus__subject__PWK-F-L-833: (914, 300)
    covariance batch 78: (914, 300), rows seen=103,744
[79/354] covariance sample Mus_musculus__subject__PWK-F-L-834: (914, 300)
    covariance batch 79: (914, 300), rows seen=104,658
[80/354] covariance sample Mus_musculus__subject__PWK-F-LR-833: (914, 300)
    covariance batch 80: (914, 300), rows seen=105,572
[81/354] covariance sample Mus_musculus__subject__PWK-F-LR-834: (914, 300)
    covariance batch 81: (914, 300), rows seen=106,486
[82/354] covariance sample Mus_musculus__subject__PWK-F-N-833: (914, 300)
    covariance batch 82: (914, 300), rows seen=107,400
[83/354] covariance sample Mus_musculus__subject__PWK-F-N-834: (914, 300)
    covariance batch 83: (914, 300), rows seen=108,314
[84/354] covariance sample Mus_musculus__subject__PWK-F-R-833: (762, 300)
    covariance batch 84: (762, 300), rows seen=109,076
[85/354] covariance sample Mus_musculus__subject__PWK-F-R-834: (914, 300)
    covariance batch 85: (914, 300), rows seen=109,990
[86/354] covariance sample Mus_musculus__subject__PWK-M-L-831: (914, 300)
    covariance batch 86: (914, 300), rows seen=110,904
[87/354] covariance sample Mus_musculus__subject__PWK-M-L-832: (914, 300)
    covariance batch 87: (914, 300), rows seen=111,818
[88/354] covariance sample Mus_musculus__subject__PWK-M-LR-831: (914, 300)
    covariance batch 88: (914, 300), rows seen=112,732
[89/354] covariance sample Mus_musculus__subject__PWK-M-LR-832: (609, 300)
    covariance batch 89: (609, 300), rows seen=113,341
[90/354] covariance sample Mus_musculus__subject__PWK-M-N-831: (914, 300)
    covariance batch 90: (914, 300), rows seen=114,255
[91/354] covariance sample Mus_musculus__subject__PWK-M-N-832: (914, 300)
    covariance batch 91: (914, 300), rows seen=115,169
[92/354] covariance sample Mus_musculus__subject__PWK-M-R-831: (914, 300)
    covariance batch 92: (914, 300), rows seen=116,083
[93/354] covariance sample Mus_musculus__subject__PWK-M-R-832: (914, 300)
    covariance batch 93: (914, 300), rows seen=116,997
[94/354] covariance sample Mus_musculus__subject__WSB-F-L-235: (152, 300)
    covariance batch 94: (152, 300), rows seen=117,149
[95/354] covariance sample Mus_musculus__subject__WSB-F-L-236: (152, 300)
    covariance batch 95: (152, 300), rows seen=117,301
[96/354] covariance sample Mus_musculus__subject__WSB-F-LR-235: (305, 300)
    covariance batch 96: (305, 300), rows seen=117,606
[97/354] covariance sample Mus_musculus__subject__WSB-F-LR-236: (305, 300)
    covariance batch 97: (305, 300), rows seen=117,911
[98/354] covariance sample Mus_musculus__subject__WSB-F-N-235: (305, 300)
    covariance batch 98: (305, 300), rows seen=118,216
[99/354] covariance sample Mus_musculus__subject__WSB-F-R-235: (152, 300)
    covariance batch 99: (152, 300), rows seen=118,368
[100/354] covariance sample Mus_musculus__subject__WSB-F-R-236: (152, 300)
    covariance batch 100: (152, 300), rows seen=118,520
[101/354] covariance sample Mus_musculus__subject__WSB-M-2L-234: (305, 300)
    covariance batch 101: (305, 300), rows seen=118,825
[102/354] covariance sample Mus_musculus__subject__WSB-M-L-233: (305, 300)
    covariance batch 102: (305, 300), rows seen=119,130
[103/354] covariance sample Mus_musculus__subject__WSB-M-L-234: (305, 300)
    covariance batch 103: (305, 300), rows seen=119,435
[104/354] covariance sample Mus_musculus__subject__WSB-M-LR-233: (305, 300)
    covariance batch 104: (305, 300), rows seen=119,740
[105/354] covariance sample Mus_musculus__subject__WSB-M-LR-234: (305, 300)
    covariance batch 105: (305, 300), rows seen=120,045
[106/354] covariance sample Mus_musculus__subject__WSB-M-N-234: (305, 300)
    covariance batch 106: (305, 300), rows seen=120,350
[107/354] covariance sample Mus_musculus__subject__WSB-M-R-233: (305, 300)
    covariance batch 107: (305, 300), rows seen=120,655
[108/354] covariance sample Mus_musculus__subject__WSB-M-R-234: (305, 300)
    covariance batch 108: (305, 300), rows seen=120,960
[109/354] covariance sample Mus_spretus__subject__SPRET-F-L-730: (4032, 300)
    covariance batch 109: (4032, 300), rows seen=124,992
[110/354] covariance sample Mus_spretus__subject__SPRET-F-L-732: (4032, 300)
    covariance batch 110: (4032, 300), rows seen=129,024
[111/354] covariance sample Mus_spretus__subject__SPRET-F-L-742: (4032, 300)
    covariance batch 111: (4032, 300), rows seen=133,056
[112/354] covariance sample Mus_spretus__subject__SPRET-F-LR-730: (4032, 300)
    covariance batch 112: (4032, 300), rows seen=137,088
[113/354] covariance sample Mus_spretus__subject__SPRET-F-N-731: (2688, 300)
    covariance batch 113: (2688, 300), rows seen=139,776
[114/354] covariance sample Mus_spretus__subject__SPRET-F-N-744: (4032, 300)
    covariance batch 114: (4032, 300), rows seen=143,808
[115/354] covariance sample Mus_spretus__subject__SPRET-F-N-745: (4032, 300)
    covariance batch 115: (4032, 300), rows seen=147,840
[116/354] covariance sample Mus_spretus__subject__SPRET-F-R-730: (4032, 300)
    covariance batch 116: (4032, 300), rows seen=151,872
[117/354] covariance sample Mus_spretus__subject__SPRET-F-R-732: (4032, 300)
    covariance batch 117: (4032, 300), rows seen=155,904
[118/354] covariance sample Mus_spretus__subject__SPRET-F-R-742: (2688, 300)
    covariance batch 118: (2688, 300), rows seen=158,592
[119/354] covariance sample Mus_spretus__subject__SPRET-F-R-743: (2688, 300)
    covariance batch 119: (2688, 300), rows seen=161,280
[120/354] covariance sample Mus_spretus__subject__SPRET-M-L-728: (4032, 300)
    covariance batch 120: (4032, 300), rows seen=165,312
[121/354] covariance sample Mus_spretus__subject__SPRET-M-L-729: (4032, 300)
    covariance batch 121: (4032, 300), rows seen=169,344
[122/354] covariance sample Mus_spretus__subject__SPRET-M-L-733: (4032, 300)
    covariance batch 122: (4032, 300), rows seen=173,376
[123/354] covariance sample Mus_spretus__subject__SPRET-M-R-729: (4032, 300)
    covariance batch 123: (4032, 300), rows seen=177,408
[124/354] covariance sample Mus_spretus__subject__SPRET-M-R-733: (4032, 300)
    covariance batch 124: (4032, 300), rows seen=181,440
[125/354] covariance sample Peromyscus_californicus__subject__38824.0: (2520, 300)
    covariance batch 125: (2520, 300), rows seen=183,960
[126/354] covariance sample Peromyscus_californicus__subject__38825.0: (2520, 300)
    covariance batch 126: (2520, 300), rows seen=186,480
[127/354] covariance sample Peromyscus_californicus__subject__38826.0: (5040, 300)
    covariance batch 127: (5040, 300), rows seen=191,520
[128/354] covariance sample Peromyscus_californicus__subject__38827.0: (2520, 300)
    covariance batch 128: (2520, 300), rows seen=194,040
[129/354] covariance sample Peromyscus_californicus__subject__39356.0: (2520, 300)
    covariance batch 129: (2520, 300), rows seen=196,560
[130/354] covariance sample Peromyscus_californicus__subject__39357.0: (2520, 300)
    covariance batch 130: (2520, 300), rows seen=199,080
[131/354] covariance sample Peromyscus_californicus__subject__39358.0: (2520, 300)
    covariance batch 131: (2520, 300), rows seen=201,600
[132/354] covariance sample Peromyscus_californicus__subject__39359.0: (2520, 300)
    covariance batch 132: (2520, 300), rows seen=204,120
[133/354] covariance sample Peromyscus_californicus__subject__39360.0: (2520, 300)
    covariance batch 133: (2520, 300), rows seen=206,640
[134/354] covariance sample Peromyscus_californicus__subject__40227.0: (2520, 300)
    covariance batch 134: (2520, 300), rows seen=209,160
[135/354] covariance sample Peromyscus_californicus__subject__40407.0: (2520, 300)
    covariance batch 135: (2520, 300), rows seen=211,680
[136/354] covariance sample Peromyscus_californicus__subject__40447.0: (2520, 300)
    covariance batch 136: (2520, 300), rows seen=214,200
[137/354] covariance sample Peromyscus_californicus__subject__40594.0: (2520, 300)
    covariance batch 137: (2520, 300), rows seen=216,720
[138/354] covariance sample Peromyscus_californicus__subject__40595.0: (2520, 300)
    covariance batch 138: (2520, 300), rows seen=219,240
[139/354] covariance sample Peromyscus_californicus__subject__40663.0: (2520, 300)
    covariance batch 139: (2520, 300), rows seen=221,760
[140/354] covariance sample Peromyscus_californicus__subject__40664.0: (2520, 300)
    covariance batch 140: (2520, 300), rows seen=224,280
[141/354] covariance sample Peromyscus_californicus__subject__40774.0: (2520, 300)
    covariance batch 141: (2520, 300), rows seen=226,800
[142/354] covariance sample Peromyscus_californicus__subject__40775.0: (2520, 300)
    covariance batch 142: (2520, 300), rows seen=229,320
[143/354] covariance sample Peromyscus_californicus__subject__40880.0: (2520, 300)
    covariance batch 143: (2520, 300), rows seen=231,840
[144/354] covariance sample Peromyscus_californicus__subject__40881.0: (2520, 300)
    covariance batch 144: (2520, 300), rows seen=234,360
[145/354] covariance sample Peromyscus_californicus__subject__40882.0: (2520, 300)
    covariance batch 145: (2520, 300), rows seen=236,880
[146/354] covariance sample Peromyscus_californicus__subject__41042.0: (2520, 300)
    covariance batch 146: (2520, 300), rows seen=239,400
[147/354] covariance sample Peromyscus_californicus__subject__41043.0: (2520, 300)
    covariance batch 147: (2520, 300), rows seen=241,920
[148/354] covariance sample Peromyscus_gossypinus__subject__37988.0: (3024, 300)
    covariance batch 148: (3024, 300), rows seen=244,944
[149/354] covariance sample Peromyscus_gossypinus__subject__37989.0: (3024, 300)
    covariance batch 149: (3024, 300), rows seen=247,968
[150/354] covariance sample Peromyscus_gossypinus__subject__37990.0: (3024, 300)
    covariance batch 150: (3024, 300), rows seen=250,992
[151/354] covariance sample Peromyscus_gossypinus__subject__38033.0: (3024, 300)
    covariance batch 151: (3024, 300), rows seen=254,016
[152/354] covariance sample Peromyscus_gossypinus__subject__38291.0: (3024, 300)

In [5]:
def save_shared_pca_loadings_per_species(
    pca,
    n_components,
    global_ids,
    output_path,
    feature_names=None,
):
    """
    Save shared PCA loadings in long format.

    Each row represents:
        species × principal component × original feature

    Because the PCA was fitted on pooled cross-species data, the loading values
    are identical for every species. Repeating them by species makes subsequent
    species-level joins and analyses straightforward.
    """
    components = np.asarray(
        pca.components_[:n_components],
        dtype=float,
    )

    n_features = components.shape[1]

    if feature_names is None:
        feature_names = [f'feature_{i}' for i in range(n_features)]
    else:
        feature_names = list(feature_names)

    if len(feature_names) != n_features:
        raise ValueError(
            f'Expected {n_features} feature names, '
            f'but received {len(feature_names)}.'
        )

    species_names = sorted({
        parse_global_id(global_id)[0]
        for global_id in global_ids
    })

    loading_rows = []

    for species in species_names:
        for pc_index in range(n_components):
            explained_variance = float(
                pca.explained_variance_[pc_index]
            )
            explained_variance_ratio = float(
                pca.explained_variance_ratio_[pc_index]
            )
            cumulative_variance_ratio = float(
                np.sum(pca.explained_variance_ratio_[:pc_index + 1])
            )

            for feature_index, feature_name in enumerate(feature_names):
                loading = float(components[pc_index, feature_index])

                loading_rows.append({
                    'species': species,
                    'component': pc_index + 1,
                    'component_label': f'PC{pc_index + 1}',
                    'feature_index': feature_index,
                    'feature_name': feature_name,
                    'loading': loading,
                    'absolute_loading': abs(loading),
                    'squared_loading': loading ** 2,
                    'explained_variance': explained_variance,
                    'explained_variance_ratio': explained_variance_ratio,
                    'cumulative_variance_ratio': cumulative_variance_ratio,
                })

    loadings_df = pd.DataFrame(loading_rows)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    loadings_df.to_csv(output_path, index=False)

    print(
        f'Saved shared PCA loadings for {len(species_names)} species: '
        f'{output_path}'
    )
    print(
        f'CSV shape: {loadings_df.shape}; '
        f'{n_components} PCs × {n_features} features × '
        f'{len(species_names)} species'
    )

    return loadings_df


shared_pca_loadings = save_shared_pca_loadings_per_species(
    pca=pre_wavelet_pca,
    n_components=pre_wavelet_n_components,
    global_ids=global_ids,
    output_path=RUN_ROOT / 'pre_wavelet_shared_pca_loadings_per_species.csv',
)

Saved shared PCA loadings for 8 species: /Users/meganbishop/slowmodeevo/outputs/single_species_distance_comparison/pca_multispecies_evensamp/pre_wavelet_shared_pca_loadings_per_species.csv
CSV shape: (67200, 11); 28 PCs × 300 features × 8 species

## 5. Wavelet Transform And PCA After Wavelets

In [6]:
def load_pre_wavelet_pca_trace(pipeline_species, individual_id, dataset_name=None):
    species, source_individual_id = parse_global_id(individual_id)
    bundle = base_loader(species, individual_id=source_individual_id, dataset_name=REPRESENTATION_NAME)
    transformed = pre_wavelet_pca.transform(bundle['X']).astype(np.float32, copy=False)
    bundle['X'] = transformed[:, :pre_wavelet_n_components]
    bundle['species_folder'] = species
    bundle['source_individual_id'] = source_individual_id
    bundle['individual_id'] = str(individual_id)
    bundle['dataset_name'] = dataset_name or DATASET_NAME_AFTER_PRE_PCA
    bundle['pre_wavelet_pca_checkpoint'] = str(RUN_ROOT / 'pre_wavelet_pca95_checkpoint.pkl')
    return bundle

projection_result = pup.prepare_pooled_individual_projections(
    pipeline_species='all_species',
    individual_ids=global_ids,
    load_individual_trace_fn=load_pre_wavelet_pca_trace,
    dataset_name=DATASET_NAME_AFTER_PRE_PCA,
    fs=FS_HZ,
    fmin=FMIN,
    fmax=FMAX,
    n_freqs=N_FREQS,
    output_dir=RUN_ROOT,
    wavelet_subsample_factor=WAVELET_SUBSAMPLE_FACTOR,
    pca_max_components=POST_WAVELET_PCA_MAX_COMPONENTS,
    n_shuffles=5,
    pca_variance_target=POST_WAVELET_PCA_VARIANCE_TARGET,
    wavelet_dtype=np.float32,
    normalize_wavelets_for_pca=NORMALIZE_WAVELETS_FOR_PCA,
    balance_pca_samples_by_species=BALANCE_POST_WAVELET_PCA_SAMPLES_BY_SPECIES,
    pca_sample_species_labels=[parse_global_id(global_id)[0] for global_id in global_ids],
    pca_rows_per_species=POST_WAVELET_PCA_ROWS_PER_SPECIES,
    reuse_existing_wavelet_samples=REUSE_EXISTING,
    reuse_existing_projections=REUSE_EXISTING,
    save_wavelet_samples=SAVE_WAVELET_SAMPLES,
    seed=SEED,
    verbose=True,
)

metadata_by_global_id = individual_manifest.set_index('global_id').to_dict('index')
for meta in projection_result['metadata']:
    extra = metadata_by_global_id[str(meta['individual_id'])]
    meta['species'] = extra['species']
    meta['source_individual_id'] = extra['individual_id']
projection_result['input_preprocessing'] = 'pre_wavelet_pca_then_wavelet_then_post_wavelet_pca'
projection_result['pre_wavelet_pca_checkpoint'] = str(RUN_ROOT / 'pre_wavelet_pca95_checkpoint.pkl')
projection_result['pre_wavelet_pca_n_components'] = pre_wavelet_n_components
projection_result['pre_wavelet_pca_variance_target'] = float(DISTANCE_PCA_VARIANCE_TARGET)
projection_result['pre_wavelet_pca_balance_samples_by_species'] = bool(BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES)
projection_result['post_wavelet_pca_balance_samples_by_species'] = bool(BALANCE_POST_WAVELET_PCA_SAMPLES_BY_SPECIES)
projection_result['pre_wavelet_pca_fit_method'] = DISTANCE_PCA_FIT_METHOD
projection_result['post_wavelet_pca_fit_method'] = POST_WAVELET_PCA_FIT_METHOD
projection_result['run_root'] = str(RUN_ROOT)
with open(RUN_ROOT / 'projection_result.pkl', 'wb') as handle:
    pickle.dump(projection_result, handle)

pd.DataFrame({
    'component': np.arange(1, len(distance_pca_result['cumulative_variance']) + 1),
    'cumulative_variance': np.asarray(distance_pca_result['cumulative_variance'], dtype=float),
}).to_csv(RUN_ROOT / 'pre_wavelet_pca_cumulative_variance.csv', index=False)

post_cumulative = projection_result.get('pca_cumulative_variance')
if post_cumulative is not None:
    pd.DataFrame({
        'component': np.arange(1, len(post_cumulative) + 1),
        'cumulative_variance': np.asarray(post_cumulative, dtype=float),
    }).to_csv(RUN_ROOT / 'post_wavelet_pca_cumulative_variance.csv', index=False)

projection_rows = []
for meta, proj_file in zip(projection_result['metadata'], projection_result['proj_files']):
    arr = np.load(proj_file, mmap_mode='r')
    projection_rows.append({
        'global_id': str(meta['individual_id']),
        'species': meta.get('species', ''),
        'source_individual_id': meta.get('source_individual_id', ''),
        'projection_file': str(Path(proj_file).resolve()),
        'n_frames': int(arr.shape[0]),
        'n_projection_dims': int(arr.shape[1]),
    })
projection_file_manifest = pd.DataFrame(projection_rows)
projection_file_manifest.to_csv(RUN_ROOT / 'projection_files_manifest.csv', index=False)

summary = pd.DataFrame([{
    'run_name': RUN_NAME,
    'run_root': str(RUN_ROOT),
    'n_species': len(species_names),
    'n_individuals': len(global_ids),
    'pre_wavelet_pca_components': pre_wavelet_n_components,
    'pre_wavelet_pca_variance': float(distance_pca_result['cumulative_variance'][pre_wavelet_n_components - 1]),
    'post_wavelet_pca_components': int(projection_result['n_kept']),
    'post_wavelet_pca_selection_mode': projection_result.get('pca_selection_mode'),
    'post_wavelet_pca_variance_target': projection_result.get('pca_variance_target'),
    'post_wavelet_pca_target_reached': projection_result.get('pca_variance_target_reached'),
    'wavelet_subsample_factor': WAVELET_SUBSAMPLE_FACTOR,
    'normalize_wavelets_for_pca': NORMALIZE_WAVELETS_FOR_PCA,
    'pre_wavelet_pca_balance_samples_by_species': bool(BALANCE_DISTANCE_PCA_SAMPLES_BY_SPECIES),
    'post_wavelet_pca_balance_samples_by_species': bool(BALANCE_POST_WAVELET_PCA_SAMPLES_BY_SPECIES),
    'pre_wavelet_pca_fit_method': DISTANCE_PCA_FIT_METHOD,
    'post_wavelet_pca_fit_method': POST_WAVELET_PCA_FIT_METHOD,
    'projection_result': str(RUN_ROOT / 'projection_result.pkl'),
    'projection_files_manifest': str(RUN_ROOT / 'projection_files_manifest.csv'),
}])
summary.to_csv(RUN_ROOT / 'projection_generation_summary.csv', index=False)
display(summary)
display(projection_file_manifest.head())

Pass 1/3: checkpoint each individual's sampled wavelet rows (every 50 row)
  [1/354] Mus_caroli__subject__CAROLI-F-2L-741: X=(432016, 28)
  [2/354] Mus_caroli__subject__CAROLI-F-L-737: X=(648024, 28)
  [3/354] Mus_caroli__subject__CAROLI-F-L-741: X=(648024, 28)
  [4/354] Mus_caroli__subject__CAROLI-F-LR-741: X=(648024, 28)
  [5/354] Mus_caroli__subject__CAROLI-F-N-740: X=(648024, 28)
  [6/354] Mus_caroli__subject__CAROLI-F-N-741: X=(648024, 28)
  [7/354] Mus_caroli__subject__CAROLI-F-R-737: X=(648024, 28)
  [8/354] Mus_caroli__subject__CAROLI-F-R-741: X=(648024, 28)
  [9/354] Mus_caroli__subject__CAROLI-M-L-734: X=(648024, 28)
  [10/354] Mus_caroli__subject__CAROLI-M-L-735: X=(648024, 28)
  [11/354] Mus_caroli__subject__CAROLI-M-L-738: X=(648024, 28)
  [12/354] Mus_caroli__subject__CAROLI-M-LR-734: X=(432016, 28)
  [13/354] Mus_caroli__subject__CAROLI-M-N-739: X=(648024, 28)
  [14/354] Mus_caroli__subject__CAROLI-M-R-734: X=(648024, 28)
  [15/354] Mus_caroli__subject__CAROLI-M-R-738: X=(648024, 28)
  [16/354] Mus_musculus__subject__40256.0: X=(647985, 28)
  [17/354] Mus_musculus__subject__40257.0: X=(647985, 28)
  [18/354] Mus_musculus__subject__40258.0: X=(431990, 28)
  [19/354] Mus_musculus__subject__40259.0: X=(431990, 28)
  [20/354] Mus_musculus__subject__40260.0: X=(431990, 28)
  [21/354] Mus_musculus__subject__40261.0: X=(647985, 28)
  [22/354] Mus_musculus__subject__40262.0: X=(647985, 28)
  [23/354] Mus_musculus__subject__40263.0: X=(431990, 28)
  [24/354] Mus_musculus__subject__40264.0: X=(647985, 28)
  [25/354] Mus_musculus__subject__40265.0: X=(215995, 28)
  [26/354] Mus_musculus__subject__40266.0: X=(647985, 28)
  [27/354] Mus_musculus__subject__40267.0: X=(647985, 28)
  [28/354] Mus_musculus__subject__40268.0: X=(647985, 28)
  [29/354] Mus_musculus__subject__40269.0: X=(647985, 28)
  [30/354] Mus_musculus__subject__40270.0: X=(431990, 28)
  [31/354] Mus_musculus__subject__40271.0: X=(647985, 28)
  [32/354] Mus_musculus__subject__CAST-F-L-CM1: X=(1512056, 28)
  [33/354] Mus_musculus__subject__CAST-F-L-CM2: X=(1512056, 28)
  [34/354] Mus_musculus__subject__CAST-F-LR-CM1: X=(1728064, 28)
  [35/354] Mus_musculus__subject__CAST-F-LR-CM2: X=(1728064, 28)
  [36/354] Mus_musculus__subject__CAST-F-N-CM1: X=(1728064, 28)
  [37/354] Mus_musculus__subject__CAST-F-N-CM2: X=(1512056, 28)
  [38/354] Mus_musculus__subject__CAST-F-R-CM1: X=(1728064, 28)
  [39/354] Mus_musculus__subject__CAST-F-R-CM2: X=(1728064, 28)
  [40/354] Mus_musculus__subject__CAST-M-L-CM3: X=(1728064, 28)
  [41/354] Mus_musculus__subject__CAST-M-L-CM4: X=(1080040, 28)
  [42/354] Mus_musculus__subject__CAST-M-LR-CM3: X=(1728064, 28)
  [43/354] Mus_musculus__subject__CAST-M-LR-CM4: X=(1512056, 28)
  [44/354] Mus_musculus__subject__CAST-M-N-CM3: X=(1728064, 28)
  [45/354] Mus_musculus__subject__CAST-M-N-CM4: X=(1512056, 28)
  [46/354] Mus_musculus__subject__CAST-M-R-CM3: X=(1512056, 28)
  [47/354] Mus_musculus__subject__CAST-M-R-CM4: X=(1512056, 28)
  [48/354] Mus_musculus__subject__DO-F-L-143: X=(648024, 28)
  [49/354] Mus_musculus__subject__DO-F-L-144: X=(648024, 28)
  [50/354] Mus_musculus__subject__DO-F-LR-143: X=(648024, 28)
  [51/354] Mus_musculus__subject__DO-F-LR-144: X=(648024, 28)
  [52/354] Mus_musculus__subject__DO-F-N-143: X=(648024, 28)
  [53/354] Mus_musculus__subject__DO-F-N-144: X=(648024, 28)
  [54/354] Mus_musculus__subject__DO-F-R-143: X=(648024, 28)
  [55/354] Mus_musculus__subject__DO-F-R-144: X=(648024, 28)
  [56/354] Mus_musculus__subject__DO-M-2L-142: X=(648024, 28)
  [57/354] Mus_musculus__subject__DO-M-2R-142: X=(648024, 28)
  [58/354] Mus_musculus__subject__DO-M-L-141: X=(648024, 28)
  [59/354] Mus_musculus__subject__DO-M-L-142: X=(648024, 28)
  [60/354] Mus_musculus__subject__DO-M-LR-141: X=(648024, 28)
  [61/354] Mus_musculus__subject__DO-M-R-141: X=(432016, 28)
  [62/354] Mus_musculus__subject__DO-M-R-142: X=(648024, 28)
  [63/354] Mus_musculus__subject__F1-F-L-159: X=(432016, 28)
  [64/354] Mus_musculus__subject__F1-F-R-159: X=(648024, 28)
  [65/354] Mus_musculus__subject__F1-M-L-166: X=(432016, 28)
  [66/354] Mus_musculus__subject__F1-M-R-166: X=(432016, 28)
  [67/354] Mus_musculus__subject__MOLF-F-2L-133: X=(1296048, 28)
  [68/354] Mus_musculus__subject__MOLF-F-L-131: X=(1080040, 28)
  [69/354] Mus_musculus__subject__MOLF-F-L-133: X=(1296048, 28)
  [70/354] Mus_musculus__subject__MOLF-F-LR-133: X=(1728064, 28)
  [71/354] Mus_musculus__subject__MOLF-F-N-133: X=(1296048, 28)
  [72/354] Mus_musculus__subject__MOLF-F-R-131: X=(1296048, 28)
  [73/354] Mus_musculus__subject__MOLF-F-R-133: X=(1296048, 28)
  [74/354] Mus_musculus__subject__MOLF-M-L-132: X=(1512056, 28)
  [75/354] Mus_musculus__subject__MOLF-M-LR-132: X=(216008, 28)
  [76/354] Mus_musculus__subject__MOLF-M-N-132: X=(1728064, 28)
  [77/354] Mus_musculus__subject__MOLF-M-R-132: X=(1512056, 28)
  [78/354] Mus_musculus__subject__PWK-F-L-833: X=(1296048, 28)
  [79/354] Mus_musculus__subject__PWK-F-L-834: X=(1296048, 28)
  [80/354] Mus_musculus__subject__PWK-F-LR-833: X=(1296048, 28)
  [81/354] Mus_musculus__subject__PWK-F-LR-834: X=(1296048, 28)
  [82/354] Mus_musculus__subject__PWK-F-N-833: X=(1296048, 28)
  [83/354] Mus_musculus__subject__PWK-F-N-834: X=(1296048, 28)
  [84/354] Mus_musculus__subject__PWK-F-R-833: X=(1080040, 28)
  [85/354] Mus_musculus__subject__PWK-F-R-834: X=(1296048, 28)
  [86/354] Mus_musculus__subject__PWK-M-L-831: X=(1296048, 28)
  [87/354] Mus_musculus__subject__PWK-M-L-832: X=(1296048, 28)
  [88/354] Mus_musculus__subject__PWK-M-LR-831: X=(1296048, 28)
  [89/354] Mus_musculus__subject__PWK-M-LR-832: X=(864032, 28)
  [90/354] Mus_musculus__subject__PWK-M-N-831: X=(1296048, 28)
  [91/354] Mus_musculus__subject__PWK-M-N-832: X=(1296048, 28)
  [92/354] Mus_musculus__subject__PWK-M-R-831: X=(1296048, 28)
  [93/354] Mus_musculus__subject__PWK-M-R-832: X=(1296048, 28)
  [94/354] Mus_musculus__subject__WSB-F-L-235: X=(216008, 28)
  [95/354] Mus_musculus__subject__WSB-F-L-236: X=(216008, 28)
  [96/354] Mus_musculus__subject__WSB-F-LR-235: X=(432016, 28)
  [97/354] Mus_musculus__subject__WSB-F-LR-236: X=(432016, 28)
  [98/354] Mus_musculus__subject__WSB-F-N-235: X=(432016, 28)
  [99/354] Mus_musculus__subject__WSB-F-R-235: X=(216008, 28)
  [100/354] Mus_musculus__subject__WSB-F-R-236: X=(216008, 28)
  [101/354] Mus_musculus__subject__WSB-M-2L-234: X=(432016, 28)
  [102/354] Mus_musculus__subject__WSB-M-L-233: X=(432016, 28)
  [103/354] Mus_musculus__subject__WSB-M-L-234: X=(432016, 28)
  [104/354] Mus_musculus__subject__WSB-M-LR-233: X=(432016, 28)
  [105/354] Mus_musculus__subject__WSB-M-LR-234: X=(432016, 28)
  [106/354] Mus_musculus__subject__WSB-M-N-234: X=(432016, 28)
  [107/354] Mus_musculus__subject__WSB-M-R-233: X=(432016, 28)
  [108/354] Mus_musculus__subject__WSB-M-R-234: X=(432016, 28)
  [109/354] Mus_spretus__subject__SPRET-F-L-730: X=(648024, 28)
  [110/354] Mus_spretus__subject__SPRET-F-L-732: X=(648024, 28)
  [111/354] Mus_spretus__subject__SPRET-F-L-742: X=(648024, 28)
  [112/354] Mus_spretus__subject__SPRET-F-LR-730: X=(648024, 28)
  [113/354] Mus_spretus__subject__SPRET-F-N-731: X=(432016, 28)
  [114/354] Mus_spretus__subject__SPRET-F-N-744: X=(648024, 28)
  [115/354] Mus_spretus__subject__SPRET-F-N-745: X=(648024, 28)
  [116/354] Mus_spretus__subject__SPRET-F-R-730: X=(648024, 28)
  [117/354] Mus_spretus__subject__SPRET-F-R-732: X=(648024, 28)
  [118/354] Mus_spretus__subject__SPRET-F-R-742: X=(432016, 28)
  [119/354] Mus_spretus__subject__SPRET-F-R-743: X=(432016, 28)
  [120/354] Mus_spretus__subject__SPRET-M-L-728: X=(648024, 28)
  [121/354] Mus_spretus__subject__SPRET-M-L-729: X=(648024, 28)
  [122/354] Mus_spretus__subject__SPRET-M-L-733: X=(648024, 28)
  [123/354] Mus_spretus__subject__SPRET-M-R-729: X=(648024, 28)
  [124/354] Mus_spretus__subject__SPRET-M-R-733: X=(648024, 28)
  [125/354] Peromyscus_californicus__subject__38824.0: X=(215995, 28)
  [126/354] Peromyscus_californicus__subject__38825.0: X=(215995, 28)
  [127/354] Peromyscus_californicus__subject__38826.0: X=(431990, 28)
  [128/354] Peromyscus_californicus__subject__38827.0: X=(215995, 28)
  [129/354] Peromyscus_californicus__subject__39356.0: X=(215995, 28)
  [130/354] Peromyscus_californicus__subject__39357.0: X=(215995, 28)
  [131/354] Peromyscus_californicus__subject__39358.0: X=(215995, 28)
  [132/354] Peromyscus_californicus__subject__39359.0: X=(215995, 28)
  [133/354] Peromyscus_californicus__subject__39360.0: X=(215995, 28)
  [134/354] Peromyscus_californicus__subject__40227.0: X=(215995, 28)
  [135/354] Peromyscus_californicus__subject__40407.0: X=(215995, 28)
  [136/354] Peromyscus_californicus__subject__40447.0: X=(215995, 28)
  [137/354] Peromyscus_californicus__subject__40594.0: X=(215995, 28)
  [138/354] Peromyscus_californicus__subject__40595.0: X=(215995, 28)
  [139/354] Peromyscus_californicus__subject__40663.0: X=(215995, 28)
  [140/354] Peromyscus_californicus__subject__40664.0: X=(215995, 28)
  [141/354] Peromyscus_californicus__subject__40774.0: X=(215995, 28)
  [142/354] Peromyscus_californicus__subject__40775.0: X=(215995, 28)
  [143/354] Peromyscus_californicus__subject__40880.0: X=(215995, 28)
  [144/354] Peromyscus_californicus__subject__40881.0: X=(215995, 28)
  [145/354] Peromyscus_californicus__subject__40882.0: X=(215995, 28)
  [146/354] Peromyscus_californicus__subject__41042.0: X=(215995, 28)
  [147/354] Peromyscus_californicus__subject__41043.0: X=(215995, 28)
  [148/354] Peromyscus_gossypinus__subject__37988.0: X=(215995, 28)
  [149/354] Peromyscus_gossypinus__subject__37989.0: X=(215995, 28)
  [150/354] Peromyscus_gossypinus__subject__37990.0: X=(215995, 28)
  [151/354] Peromyscus_gossypinus__subject__38033.0: X=(215995, 28)
  [152/354] Peromyscus_gossypinus__subject__38291.0: X=(215995, 28)
  [153/354] Peromyscus_gossypinus__subject__38305.0: X=(215995, 28)
  [154/354] Peromyscus_gossypinus__subject__38983.0: X=(215995, 28)
  [155/354] Peromyscus_gossypinus__subject__38984.0: X=(215995, 28)
  [156/354] Peromyscus_gossypinus__subject__38985.0: X=(215995, 28)
  [157/354] Peromyscus_gossypinus__subject__38989.0: X=(215995, 28)
  [158/354] Peromyscus_gossypinus__subject__38990.0: X=(215995, 28)
  [159/354] Peromyscus_gossypinus__subject__38991.0: X=(215995, 28)
  [160/354] Peromyscus_gossypinus__subject__38992.0: X=(215995, 28)
  [161/354] Peromyscus_gossypinus__subject__38993.0: X=(215995, 28)
  [162/354] Peromyscus_gossypinus__subject__39060.0: X=(215995, 28)
  [163/354] Peromyscus_gossypinus__subject__39231.0: X=(215995, 28)
  [164/354] Peromyscus_gossypinus__subject__39232.0: X=(215995, 28)
  [165/354] Peromyscus_gossypinus__subject__39233.0: X=(215995, 28)
  [166/354] Peromyscus_gossypinus__subject__39265.0: X=(215995, 28)
  [167/354] Peromyscus_gossypinus__subject__39266.0: X=(215995, 28)
  [168/354] Peromyscus_leucopus__subject__37991.0: X=(215995, 28)
  [169/354] Peromyscus_leucopus__subject__37992.0: X=(215995, 28)
  [170/354] Peromyscus_leucopus__subject__38207.0: X=(215995, 28)
  [171/354] Peromyscus_leucopus__subject__38296.0: X=(215995, 28)
  [172/354] Peromyscus_leucopus__subject__38297.0: X=(215995, 28)
  [173/354] Peromyscus_leucopus__subject__39026.0: X=(215995, 28)
  [174/354] Peromyscus_leucopus__subject__39787.0: X=(215995, 28)
  [175/354] Peromyscus_leucopus__subject__39788.0: X=(215995, 28)
  [176/354] Peromyscus_leucopus__subject__39811.0: X=(215995, 28)
  [177/354] Peromyscus_leucopus__subject__39812.0: X=(215995, 28)
  [178/354] Peromyscus_leucopus__subject__39883.0: X=(215995, 28)
  [179/354] Peromyscus_leucopus__subject__40923.0: X=(215995, 28)
  [180/354] Peromyscus_leucopus__subject__40926.0: X=(215995, 28)
  [181/354] Peromyscus_leucopus__subject__40927.0: X=(215995, 28)
  [182/354] Peromyscus_maniculatus__subject__28247.0: X=(215995, 28)
  [183/354] Peromyscus_maniculatus__subject__28529.0: X=(215995, 28)
  [184/354] Peromyscus_maniculatus__subject__34456.0: X=(215995, 28)
  [185/354] Peromyscus_maniculatus__subject__34457.0: X=(215995, 28)
  [186/354] Peromyscus_maniculatus__subject__34459.0: X=(215995, 28)
  [187/354] Peromyscus_maniculatus__subject__37837.0: X=(215995, 28)
  [188/354] Peromyscus_maniculatus__subject__37838.0: X=(215995, 28)
  [189/354] Peromyscus_maniculatus__subject__37839.0: X=(215995, 28)
  [190/354] Peromyscus_maniculatus__subject__37950.0: X=(215995, 28)
  [191/354] Peromyscus_maniculatus__subject__37951.0: X=(215995, 28)
  [192/354] Peromyscus_maniculatus__subject__37953.0: X=(215995, 28)
  [193/354] Peromyscus_maniculatus__subject__37954.0: X=(215995, 28)
  [194/354] Peromyscus_maniculatus__subject__37955.0: X=(215995, 28)
  [195/354] Peromyscus_maniculatus__subject__37956.0: X=(215995, 28)
  [196/354] Peromyscus_maniculatus__subject__38027.0: X=(215995, 28)
  [197/354] Peromyscus_maniculatus__subject__38028.0: X=(215995, 28)
  [198/354] Peromyscus_maniculatus__subject__38029.0: X=(215995, 28)
  [199/354] Peromyscus_maniculatus__subject__38069.0: X=(215995, 28)
  [200/354] Peromyscus_maniculatus__subject__38070.0: X=(215995, 28)
  [201/354] Peromyscus_maniculatus__subject__38102.0: X=(431990, 28)
  [202/354] Peromyscus_maniculatus__subject__38103.0: X=(215995, 28)
  [203/354] Peromyscus_maniculatus__subject__38104.0: X=(215995, 28)
  [204/354] Peromyscus_maniculatus__subject__38105.0: X=(215995, 28)
  [205/354] Peromyscus_maniculatus__subject__38110.0: X=(431990, 28)
  [206/354] Peromyscus_maniculatus__subject__38111.0: X=(431990, 28)
  [207/354] Peromyscus_maniculatus__subject__38112.0: X=(431990, 28)
  [208/354] Peromyscus_maniculatus__subject__38124.0: X=(215995, 28)
  [209/354] Peromyscus_maniculatus__subject__38125.0: X=(215995, 28)
  [210/354] Peromyscus_maniculatus__subject__38126.0: X=(215995, 28)
  [211/354] Peromyscus_maniculatus__subject__38127.0: X=(215995, 28)
  [212/354] Peromyscus_maniculatus__subject__38128.0: X=(215995, 28)
  [213/354] Peromyscus_maniculatus__subject__38129.0: X=(215995, 28)
  [214/354] Peromyscus_maniculatus__subject__38130.0: X=(215995, 28)
  [215/354] Peromyscus_maniculatus__subject__38154.0: X=(431990, 28)
  [216/354] Peromyscus_maniculatus__subject__38155.0: X=(431990, 28)
  [217/354] Peromyscus_maniculatus__subject__38156.0: X=(215995, 28)
  [218/354] Peromyscus_maniculatus__subject__38157.0: X=(215995, 28)
  [219/354] Peromyscus_maniculatus__subject__38158.0: X=(215995, 28)
  [220/354] Peromyscus_maniculatus__subject__38159.0: X=(215995, 28)
  [221/354] Peromyscus_maniculatus__subject__38196.0: X=(215995, 28)
  [222/354] Peromyscus_maniculatus__subject__38197.0: X=(215995, 28)
  [223/354] Peromyscus_maniculatus__subject__38198.0: X=(215995, 28)
  [224/354] Peromyscus_maniculatus__subject__38199.0: X=(215995, 28)
  [225/354] Peromyscus_maniculatus__subject__38200.0: X=(215995, 28)
  [226/354] Peromyscus_maniculatus__subject__38201.0: X=(215995, 28)
  [227/354] Peromyscus_maniculatus__subject__38208.0: X=(215995, 28)
  [228/354] Peromyscus_maniculatus__subject__38209.0: X=(215995, 28)
  [229/354] Peromyscus_maniculatus__subject__38235.0: X=(215995, 28)
  [230/354] Peromyscus_maniculatus__subject__38246.0: X=(215995, 28)
  [231/354] Peromyscus_maniculatus__subject__38285.0: X=(215995, 28)
  [232/354] Peromyscus_maniculatus__subject__38286.0: X=(215995, 28)
  [233/354] Peromyscus_maniculatus__subject__38298.0: X=(215995, 28)
  [234/354] Peromyscus_maniculatus__subject__38299.0: X=(215995, 28)
  [235/354] Peromyscus_maniculatus__subject__38300.0: X=(215995, 28)
  [236/354] Peromyscus_maniculatus__subject__38301.0: X=(215995, 28)
  [237/354] Peromyscus_maniculatus__subject__38308.0: X=(215995, 28)
  [238/354] Peromyscus_maniculatus__subject__38309.0: X=(215995, 28)
  [239/354] Peromyscus_maniculatus__subject__38310.0: X=(215995, 28)
  [240/354] Peromyscus_maniculatus__subject__38311.0: X=(215995, 28)
  [241/354] Peromyscus_maniculatus__subject__38312.0: X=(215995, 28)
  [242/354] Peromyscus_maniculatus__subject__38313.0: X=(215995, 28)
  [243/354] Peromyscus_maniculatus__subject__38314.0: X=(215995, 28)
  [244/354] Peromyscus_maniculatus__subject__38323.0: X=(215995, 28)
  [245/354] Peromyscus_maniculatus__subject__38324.0: X=(215995, 28)
  [246/354] Peromyscus_maniculatus__subject__38407.0: X=(215995, 28)
  [247/354] Peromyscus_maniculatus__subject__38408.0: X=(215995, 28)
  [248/354] Peromyscus_maniculatus__subject__38409.0: X=(215995, 28)
  [249/354] Peromyscus_maniculatus__subject__38410.0: X=(215995, 28)
  [250/354] Peromyscus_maniculatus__subject__38411.0: X=(431990, 28)
  [251/354] Peromyscus_maniculatus__subject__38412.0: X=(215995, 28)
  [252/354] Peromyscus_maniculatus__subject__38413.0: X=(215995, 28)
  [253/354] Peromyscus_maniculatus__subject__38427.0: X=(215995, 28)
  [254/354] Peromyscus_maniculatus__subject__38428.0: X=(215995, 28)
  [255/354] Peromyscus_maniculatus__subject__38429.0: X=(215995, 28)
  [256/354] Peromyscus_maniculatus__subject__38430.0: X=(215995, 28)
  [257/354] Peromyscus_maniculatus__subject__38431.0: X=(215995, 28)
  [258/354] Peromyscus_maniculatus__subject__38508.0: X=(215995, 28)
  [259/354] Peromyscus_maniculatus__subject__38509.0: X=(215995, 28)
  [260/354] Peromyscus_maniculatus__subject__38510.0: X=(215995, 28)
  [261/354] Peromyscus_maniculatus__subject__38517.0: X=(215995, 28)
  [262/354] Peromyscus_maniculatus__subject__38518.0: X=(215995, 28)
  [263/354] Peromyscus_maniculatus__subject__38531.0: X=(215995, 28)
  [264/354] Peromyscus_maniculatus__subject__38532.0: X=(431990, 28)
  [265/354] Peromyscus_maniculatus__subject__38569.0: X=(215995, 28)
  [266/354] Peromyscus_maniculatus__subject__38572.0: X=(215995, 28)
  [267/354] Peromyscus_maniculatus__subject__38573.0: X=(215995, 28)
  [268/354] Peromyscus_maniculatus__subject__38574.0: X=(215995, 28)
  [269/354] Peromyscus_maniculatus__subject__38575.0: X=(215995, 28)
  [270/354] Peromyscus_maniculatus__subject__38576.0: X=(215995, 28)
  [271/354] Peromyscus_maniculatus__subject__38591.0: X=(215995, 28)
  [272/354] Peromyscus_maniculatus__subject__38648.0: X=(215995, 28)
  [273/354] Peromyscus_maniculatus__subject__38649.0: X=(215995, 28)
  [274/354] Peromyscus_maniculatus__subject__38779.0: X=(215995, 28)
  [275/354] Peromyscus_maniculatus__subject__38811.0: X=(215995, 28)
  [276/354] Peromyscus_maniculatus__subject__38812.0: X=(215995, 28)
  [277/354] Peromyscus_maniculatus__subject__38888.0: X=(215995, 28)
  [278/354] Peromyscus_maniculatus__subject__38889.0: X=(215995, 28)
  [279/354] Peromyscus_maniculatus__subject__38890.0: X=(215995, 28)
  [280/354] Peromyscus_maniculatus__subject__38892.0: X=(215995, 28)
  [281/354] Peromyscus_maniculatus__subject__39006.0: X=(215995, 28)
  [282/354] Peromyscus_maniculatus__subject__39007.0: X=(215995, 28)
  [283/354] Peromyscus_maniculatus__subject__39009.0: X=(215995, 28)
  [284/354] Peromyscus_maniculatus__subject__39010.0: X=(215995, 28)
  [285/354] Peromyscus_maniculatus__subject__39012.0: X=(215995, 28)
  [286/354] Peromyscus_maniculatus__subject__39013.0: X=(215995, 28)
  [287/354] Peromyscus_maniculatus__subject__39014.0: X=(215995, 28)
  [288/354] Peromyscus_maniculatus__subject__39019.0: X=(215995, 28)
  [289/354] Peromyscus_maniculatus__subject__39020.0: X=(215995, 28)
  [290/354] Peromyscus_maniculatus__subject__39043.0: X=(215995, 28)
  [291/354] Peromyscus_maniculatus__subject__39044.0: X=(431990, 28)
  [292/354] Peromyscus_maniculatus__subject__39045.0: X=(431990, 28)
  [293/354] Peromyscus_maniculatus__subject__39046.0: X=(647985, 28)
  [294/354] Peromyscus_maniculatus__subject__39257.0: X=(215995, 28)
  [295/354] Peromyscus_maniculatus__subject__39258.0: X=(215995, 28)
  [296/354] Peromyscus_maniculatus__subject__39323.0: X=(215995, 28)
  [297/354] Peromyscus_maniculatus__subject__39324.0: X=(215995, 28)
  [298/354] Peromyscus_maniculatus__subject__39325.0: X=(215995, 28)
  [299/354] Peromyscus_maniculatus__subject__39326.0: X=(215995, 28)
  [300/354] Peromyscus_maniculatus__subject__39327.0: X=(647985, 28)
  [301/354] Peromyscus_maniculatus__subject__39328.0: X=(647985, 28)

,run_name,run_root,n_species,n_individuals,pre_wavelet_pca_components,pre_wavelet_pca_variance,post_wavelet_pca_components,post_wavelet_pca_selection_mode,post_wavelet_pca_variance_target,post_wavelet_pca_target_reached,wavelet_subsample_factor,normalize_wavelets_for_pca,pre_wavelet_pca_balance_samples_by_species,post_wavelet_pca_balance_samples_by_species,pre_wavelet_pca_fit_method,post_wavelet_pca_fit_method,projection_result,projection_files_manifest
0,pca_multispecies_evensamp,/Users/meganbishop/slowmodeevo/outputs/single_...,8,354,28,0.990521,100,variance_target,0.99,False,50,True,True,True,streaming_covariance,streaming_covariance,/Users/meganbishop/slowmodeevo/outputs/single_...,/Users/meganbishop/slowmodeevo/outputs/single_...

,global_id,species,source_individual_id,projection_file,n_frames,n_projection_dims
0,Mus_caroli__subject__CAROLI-F-2L-741,Mus_caroli,CAROLI-F-2L-741,/Users/meganbishop/slowmodeevo/outputs/single_...,432016,100
1,Mus_caroli__subject__CAROLI-F-L-737,Mus_caroli,CAROLI-F-L-737,/Users/meganbishop/slowmodeevo/outputs/single_...,648024,100
2,Mus_caroli__subject__CAROLI-F-L-741,Mus_caroli,CAROLI-F-L-741,/Users/meganbishop/slowmodeevo/outputs/single_...,648024,100
3,Mus_caroli__subject__CAROLI-F-LR-741,Mus_caroli,CAROLI-F-LR-741,/Users/meganbishop/slowmodeevo/outputs/single_...,648024,100
4,Mus_caroli__subject__CAROLI-F-N-740,Mus_caroli,CAROLI-F-N-740,/Users/meganbishop/slowmodeevo/outputs/single_...,648024,100

## 6. Optional Slow-Mode Estimation From Saved Projections

In [7]:
if RUN_SLOW_MODES:
    proj_files = [str(Path(path)) for path in projection_result['proj_files']]
    state_result = pup.assign_pooled_states_from_projections(
        proj_files=proj_files,
        d_embed=D_EMBED,
        N=N_CLUSTERS,
        output_dir=RUN_ROOT,
        kmeans_subsample_factor=KMEANS_SUBSAMPLE_FACTOR,
        seed=SEED,
        kmeans_n_init=KMEANS_N_INIT,
        save_states=True,
        verbose=True,
    )
    slow_result = pup.compute_pooled_slow_modes(
        state_result['states_list'],
        fs=FS_HZ,
        tau_seconds=TAU_SECONDS,
        N=N_CLUSTERS,
        M=N_BASINS,
        use_recursive_arms=USE_RECURSIVE_ARMS,
    )
    final_dir = RUN_ROOT / 'final_outputs'
    saved = pup.save_pooled_outputs(
        output_dir=final_dir,
        species='all_species',
        individual_ids=global_ids,
        state_files=state_result['state_files'],
        states_list=state_result['states_list'],
        T=slow_result['T'],
        pi=slow_result['pi'],
        evals=slow_result['evals'],
        evecs=slow_result['evecs'],
        chi=slow_result['gpcca']['chi'],
        parameters={
            'run_name': RUN_NAME,
            'dataset': DATASET_NAME_AFTER_PRE_PCA,
            'fs': FS_HZ,
            'fmin': FMIN,
            'fmax': FMAX,
            'n_freqs': N_FREQS,
            'pre_wavelet_pca_components': pre_wavelet_n_components,
            'post_wavelet_pca_components': int(projection_result['n_kept']),
            'd_embed': D_EMBED,
            'N': N_CLUSTERS,
            'kmeans_subsample_factor': KMEANS_SUBSAMPLE_FACTOR,
            'tau_seconds': TAU_SECONDS,
            'lag_frames': slow_result['lag'],
            'M': N_BASINS,
            'use_recursive_arms': USE_RECURSIVE_ARMS,
        },
        metadata=projection_result['metadata'],
        arm_tree=slow_result.get('arm_tree'),
    )
    with open(RUN_ROOT / 'slow_mode_result.pkl', 'wb') as handle:
        pickle.dump({
            'state_files': state_result['state_files'],
            'd_embed': D_EMBED,
            'N': N_CLUSTERS,
            'kmeans_subsample_factor': KMEANS_SUBSAMPLE_FACTOR,
            'lag': slow_result['lag'],
            'tau_seconds': TAU_SECONDS,
            'M': N_BASINS,
            'final_outputs': str(final_dir),
            'saved': saved,
        }, handle)
    print(f'Saved slow-mode outputs under {final_dir}')
else:
    print('RUN_SLOW_MODES is False; projections are ready for clustering notebooks.')

Fitting shared k-means: d_embed=10, N=1000, sample every 20 embedded rows
  k-means sample matrix = (7981351, 1000)
Assigning every embedded frame to shared clusters
  [1/354] Mus_caroli__subject__CAROLI-F-2L-741: assigning states
  [2/354] Mus_caroli__subject__CAROLI-F-L-737: assigning states
  [3/354] Mus_caroli__subject__CAROLI-F-L-741: assigning states
  [4/354] Mus_caroli__subject__CAROLI-F-LR-741: assigning states
  [5/354] Mus_caroli__subject__CAROLI-F-N-740: assigning states
  [6/354] Mus_caroli__subject__CAROLI-F-N-741: assigning states
  [7/354] Mus_caroli__subject__CAROLI-F-R-737: assigning states
  [8/354] Mus_caroli__subject__CAROLI-F-R-741: assigning states
  [9/354] Mus_caroli__subject__CAROLI-M-L-734: assigning states
  [10/354] Mus_caroli__subject__CAROLI-M-L-735: assigning states
  [11/354] Mus_caroli__subject__CAROLI-M-L-738: assigning states
  [12/354] Mus_caroli__subject__CAROLI-M-LR-734: assigning states
  [13/354] Mus_caroli__subject__CAROLI-M-N-739: assigning states
  [14/354] Mus_caroli__subject__CAROLI-M-R-734: assigning states
  [15/354] Mus_caroli__subject__CAROLI-M-R-738: assigning states
  [16/354] Mus_musculus__subject__40256.0: assigning states
  [17/354] Mus_musculus__subject__40257.0: assigning states
  [18/354] Mus_musculus__subject__40258.0: assigning states
  [19/354] Mus_musculus__subject__40259.0: assigning states
  [20/354] Mus_musculus__subject__40260.0: assigning states
  [21/354] Mus_musculus__subject__40261.0: assigning states
  [22/354] Mus_musculus__subject__40262.0: assigning states
  [23/354] Mus_musculus__subject__40263.0: assigning states
  [24/354] Mus_musculus__subject__40264.0: assigning states
  [25/354] Mus_musculus__subject__40265.0: assigning states
  [26/354] Mus_musculus__subject__40266.0: assigning states
  [27/354] Mus_musculus__subject__40267.0: assigning states
  [28/354] Mus_musculus__subject__40268.0: assigning states
  [29/354] Mus_musculus__subject__40269.0: assigning states
  [30/354] Mus_musculus__subject__40270.0: assigning states
  [31/354] Mus_musculus__subject__40271.0: assigning states
  [32/354] Mus_musculus__subject__CAST-F-L-CM1: assigning states
  [33/354] Mus_musculus__subject__CAST-F-L-CM2: assigning states
  [34/354] Mus_musculus__subject__CAST-F-LR-CM1: assigning states
  [35/354] Mus_musculus__subject__CAST-F-LR-CM2: assigning states
  [36/354] Mus_musculus__subject__CAST-F-N-CM1: assigning states
  [37/354] Mus_musculus__subject__CAST-F-N-CM2: assigning states
  [38/354] Mus_musculus__subject__CAST-F-R-CM1: assigning states
  [39/354] Mus_musculus__subject__CAST-F-R-CM2: assigning states
  [40/354] Mus_musculus__subject__CAST-M-L-CM3: assigning states
  [41/354] Mus_musculus__subject__CAST-M-L-CM4: assigning states
  [42/354] Mus_musculus__subject__CAST-M-LR-CM3: assigning states
  [43/354] Mus_musculus__subject__CAST-M-LR-CM4: assigning states
  [44/354] Mus_musculus__subject__CAST-M-N-CM3: assigning states
  [45/354] Mus_musculus__subject__CAST-M-N-CM4: assigning states
  [46/354] Mus_musculus__subject__CAST-M-R-CM3: assigning states
  [47/354] Mus_musculus__subject__CAST-M-R-CM4: assigning states
  [48/354] Mus_musculus__subject__DO-F-L-143: assigning states
  [49/354] Mus_musculus__subject__DO-F-L-144: assigning states
  [50/354] Mus_musculus__subject__DO-F-LR-143: assigning states
  [51/354] Mus_musculus__subject__DO-F-LR-144: assigning states
  [52/354] Mus_musculus__subject__DO-F-N-143: assigning states
  [53/354] Mus_musculus__subject__DO-F-N-144: assigning states
  [54/354] Mus_musculus__subject__DO-F-R-143: assigning states
  [55/354] Mus_musculus__subject__DO-F-R-144: assigning states
  [56/354] Mus_musculus__subject__DO-M-2L-142: assigning states
  [57/354] Mus_musculus__subject__DO-M-2R-142: assigning states
  [58/354] Mus_musculus__subject__DO-M-L-141: assigning states
  [59/354] Mus_musculus__subject__DO-M-L-142: assigning states
  [60/354] Mus_musculus__subject__DO-M-LR-141: assigning states
  [61/354] Mus_musculus__subject__DO-M-R-141: assigning states
  [62/354] Mus_musculus__subject__DO-M-R-142: assigning states
  [63/354] Mus_musculus__subject__F1-F-L-159: assigning states
  [64/354] Mus_musculus__subject__F1-F-R-159: assigning states
  [65/354] Mus_musculus__subject__F1-M-L-166: assigning states
  [66/354] Mus_musculus__subject__F1-M-R-166: assigning states
  [67/354] Mus_musculus__subject__MOLF-F-2L-133: assigning states
  [68/354] Mus_musculus__subject__MOLF-F-L-131: assigning states
  [69/354] Mus_musculus__subject__MOLF-F-L-133: assigning states
  [70/354] Mus_musculus__subject__MOLF-F-LR-133: assigning states
  [71/354] Mus_musculus__subject__MOLF-F-N-133: assigning states
  [72/354] Mus_musculus__subject__MOLF-F-R-131: assigning states
  [73/354] Mus_musculus__subject__MOLF-F-R-133: assigning states
  [74/354] Mus_musculus__subject__MOLF-M-L-132: assigning states
  [75/354] Mus_musculus__subject__MOLF-M-LR-132: assigning states
  [76/354] Mus_musculus__subject__MOLF-M-N-132: assigning states
  [77/354] Mus_musculus__subject__MOLF-M-R-132: assigning states
  [78/354] Mus_musculus__subject__PWK-F-L-833: assigning states
  [79/354] Mus_musculus__subject__PWK-F-L-834: assigning states
  [80/354] Mus_musculus__subject__PWK-F-LR-833: assigning states
  [81/354] Mus_musculus__subject__PWK-F-LR-834: assigning states
  [82/354] Mus_musculus__subject__PWK-F-N-833: assigning states
  [83/354] Mus_musculus__subject__PWK-F-N-834: assigning states
  [84/354] Mus_musculus__subject__PWK-F-R-833: assigning states
  [85/354] Mus_musculus__subject__PWK-F-R-834: assigning states
  [86/354] Mus_musculus__subject__PWK-M-L-831: assigning states
  [87/354] Mus_musculus__subject__PWK-M-L-832: assigning states
  [88/354] Mus_musculus__subject__PWK-M-LR-831: assigning states
  [89/354] Mus_musculus__subject__PWK-M-LR-832: assigning states
  [90/354] Mus_musculus__subject__PWK-M-N-831: assigning states
  [91/354] Mus_musculus__subject__PWK-M-N-832: assigning states
  [92/354] Mus_musculus__subject__PWK-M-R-831: assigning states
  [93/354] Mus_musculus__subject__PWK-M-R-832: assigning states
  [94/354] Mus_musculus__subject__WSB-F-L-235: assigning states
  [95/354] Mus_musculus__subject__WSB-F-L-236: assigning states
  [96/354] Mus_musculus__subject__WSB-F-LR-235: assigning states
  [97/354] Mus_musculus__subject__WSB-F-LR-236: assigning states
  [98/354] Mus_musculus__subject__WSB-F-N-235: assigning states
  [99/354] Mus_musculus__subject__WSB-F-R-235: assigning states
  [100/354] Mus_musculus__subject__WSB-F-R-236: assigning states
  [101/354] Mus_musculus__subject__WSB-M-2L-234: assigning states
  [102/354] Mus_musculus__subject__WSB-M-L-233: assigning states
  [103/354] Mus_musculus__subject__WSB-M-L-234: assigning states
  [104/354] Mus_musculus__subject__WSB-M-LR-233: assigning states
  [105/354] Mus_musculus__subject__WSB-M-LR-234: assigning states
  [106/354] Mus_musculus__subject__WSB-M-N-234: assigning states
  [107/354] Mus_musculus__subject__WSB-M-R-233: assigning states
  [108/354] Mus_musculus__subject__WSB-M-R-234: assigning states
  [109/354] Mus_spretus__subject__SPRET-F-L-730: assigning states
  [110/354] Mus_spretus__subject__SPRET-F-L-732: assigning states
  [111/354] Mus_spretus__subject__SPRET-F-L-742: assigning states
  [112/354] Mus_spretus__subject__SPRET-F-LR-730: assigning states
  [113/354] Mus_spretus__subject__SPRET-F-N-731: assigning states
  [114/354] Mus_spretus__subject__SPRET-F-N-744: assigning states
  [115/354] Mus_spretus__subject__SPRET-F-N-745: assigning states
  [116/354] Mus_spretus__subject__SPRET-F-R-730: assigning states
  [117/354] Mus_spretus__subject__SPRET-F-R-732: assigning states
  [118/354] Mus_spretus__subject__SPRET-F-R-742: assigning states
  [119/354] Mus_spretus__subject__SPRET-F-R-743: assigning states
  [120/354] Mus_spretus__subject__SPRET-M-L-728: assigning states
  [121/354] Mus_spretus__subject__SPRET-M-L-729: assigning states
  [122/354] Mus_spretus__subject__SPRET-M-L-733: assigning states
  [123/354] Mus_spretus__subject__SPRET-M-R-729: assigning states
  [124/354] Mus_spretus__subject__SPRET-M-R-733: assigning states
  [125/354] Peromyscus_californicus__subject__38824.0: assigning states
  [126/354] Peromyscus_californicus__subject__38825.0: assigning states
  [127/354] Peromyscus_californicus__subject__38826.0: assigning states
  [128/354] Peromyscus_californicus__subject__38827.0: assigning states
  [129/354] Peromyscus_californicus__subject__39356.0: assigning states
  [130/354] Peromyscus_californicus__subject__39357.0: assigning states
  [131/354] Peromyscus_californicus__subject__39358.0: assigning states
  [132/354] Peromyscus_californicus__subject__39359.0: assigning states
  [133/354] Peromyscus_californicus__subject__39360.0: assigning states
  [134/354] Peromyscus_californicus__subject__40227.0: assigning states
  [135/354] Peromyscus_californicus__subject__40407.0: assigning states
  [136/354] Peromyscus_californicus__subject__40447.0: assigning states
  [137/354] Peromyscus_californicus__subject__40594.0: assigning states
  [138/354] Peromyscus_californicus__subject__40595.0: assigning states
  [139/354] Peromyscus_californicus__subject__40663.0: assigning states
  [140/354] Peromyscus_californicus__subject__40664.0: assigning states
  [141/354] Peromyscus_californicus__subject__40774.0: assigning states
  [142/354] Peromyscus_californicus__subject__40775.0: assigning states
  [143/354] Peromyscus_californicus__subject__40880.0: assigning states
  [144/354] Peromyscus_californicus__subject__40881.0: assigning states
  [145/354] Peromyscus_californicus__subject__40882.0: assigning states
  [146/354] Peromyscus_californicus__subject__41042.0: assigning states
  [147/354] Peromyscus_californicus__subject__41043.0: assigning states
  [148/354] Peromyscus_gossypinus__subject__37988.0: assigning states
  [149/354] Peromyscus_gossypinus__subject__37989.0: assigning states
  [150/354] Peromyscus_gossypinus__subject__37990.0: assigning states
  [151/354] Peromyscus_gossypinus__subject__38033.0: assigning states
  [152/354] Peromyscus_gossypinus__subject__38291.0: assigning states
  [153/354] Peromyscus_gossypinus__subject__38305.0: assigning states
  [154/354] Peromyscus_gossypinus__subject__38983.0: assigning states
  [155/354] Peromyscus_gossypinus__subject__38984.0: assigning states
  [156/354] Peromyscus_gossypinus__subject__38985.0: assigning states
  [157/354] Peromyscus_gossypinus__subject__38989.0: assigning states
  [158/354] Peromyscus_gossypinus__subject__38990.0: assigning states
  [159/354] Peromyscus_gossypinus__subject__38991.0: assigning states
  [160/354] Peromyscus_gossypinus__subject__38992.0: assigning states
  [161/354] Peromyscus_gossypinus__subject__38993.0: assigning states
  [162/354] Peromyscus_gossypinus__subject__39060.0: assigning states
  [163/354] Peromyscus_gossypinus__subject__39231.0: assigning states
  [164/354] Peromyscus_gossypinus__subject__39232.0: assigning states
  [165/354] Peromyscus_gossypinus__subject__39233.0: assigning states
  [166/354] Peromyscus_gossypinus__subject__39265.0: assigning states
  [167/354] Peromyscus_gossypinus__subject__39266.0: assigning states
  [168/354] Peromyscus_leucopus__subject__37991.0: assigning states
  [169/354] Peromyscus_leucopus__subject__37992.0: assigning states
  [170/354] Peromyscus_leucopus__subject__38207.0: assigning states
  [171/354] Peromyscus_leucopus__subject__38296.0: assigning states
  [172/354] Peromyscus_leucopus__subject__38297.0: assigning states
  [173/354] Peromyscus_leucopus__subject__39026.0: assigning states
  [174/354] Peromyscus_leucopus__subject__39787.0: assigning states
  [175/354] Peromyscus_leucopus__subject__39788.0: assigning states
  [176/354] Peromyscus_leucopus__subject__39811.0: assigning states
  [177/354] Peromyscus_leucopus__subject__39812.0: assigning states
  [178/354] Peromyscus_leucopus__subject__39883.0: assigning states
  [179/354] Peromyscus_leucopus__subject__40923.0: assigning states
  [180/354] Peromyscus_leucopus__subject__40926.0: assigning states
  [181/354] Peromyscus_leucopus__subject__40927.0: assigning states
  [182/354] Peromyscus_maniculatus__subject__28247.0: assigning states
  [183/354] Peromyscus_maniculatus__subject__28529.0: assigning states
  [184/354] Peromyscus_maniculatus__subject__34456.0: assigning states
  [185/354] Peromyscus_maniculatus__subject__34457.0: assigning states
  [186/354] Peromyscus_maniculatus__subject__34459.0: assigning states
  [187/354] Peromyscus_maniculatus__subject__37837.0: assigning states
  [188/354] Peromyscus_maniculatus__subject__37838.0: assigning states
  [189/354] Peromyscus_maniculatus__subject__37839.0: assigning states
  [190/354] Peromyscus_maniculatus__subject__37950.0: assigning states
  [191/354] Peromyscus_maniculatus__subject__37951.0: assigning states
  [192/354] Peromyscus_maniculatus__subject__37953.0: assigning states
  [193/354] Peromyscus_maniculatus__subject__37954.0: assigning states
  [194/354] Peromyscus_maniculatus__subject__37955.0: assigning states
  [195/354] Peromyscus_maniculatus__subject__37956.0: assigning states
  [196/354] Peromyscus_maniculatus__subject__38027.0: assigning states
  [197/354] Peromyscus_maniculatus__subject__38028.0: assigning states
  [198/354] Peromyscus_maniculatus__subject__38029.0: assigning states
  [199/354] Peromyscus_maniculatus__subject__38069.0: assigning states
  [200/354] Peromyscus_maniculatus__subject__38070.0: assigning states
  [201/354] Peromyscus_maniculatus__subject__38102.0: assigning states
  [202/354] Peromyscus_maniculatus__subject__38103.0: assigning states
  [203/354] Peromyscus_maniculatus__subject__38104.0: assigning states
  [204/354] Peromyscus_maniculatus__subject__38105.0: assigning states
  [205/354] Peromyscus_maniculatus__subject__38110.0: assigning states
  [206/354] Peromyscus_maniculatus__subject__38111.0: assigning states
  [207/354] Peromyscus_maniculatus__subject__38112.0: assigning states
  [208/354] Peromyscus_maniculatus__subject__38124.0: assigning states
  [209/354] Peromyscus_maniculatus__subject__38125.0: assigning states
  [210/354] Peromyscus_maniculatus__subject__38126.0: assigning states
  [211/354] Peromyscus_maniculatus__subject__38127.0: assigning states
  [212/354] Peromyscus_maniculatus__subject__38128.0: assigning states
  [213/354] Peromyscus_maniculatus__subject__38129.0: assigning states
  [214/354] Peromyscus_maniculatus__subject__38130.0: assigning states
  [215/354] Peromyscus_maniculatus__subject__38154.0: assigning states
  [216/354] Peromyscus_maniculatus__subject__38155.0: assigning states
  [217/354] Peromyscus_maniculatus__subject__38156.0: assigning states
  [218/354] Peromyscus_maniculatus__subject__38157.0: assigning states
  [219/354] Peromyscus_maniculatus__subject__38158.0: assigning states
  [220/354] Peromyscus_maniculatus__subject__38159.0: assigning states
  [221/354] Peromyscus_maniculatus__subject__38196.0: assigning states
  [222/354] Peromyscus_maniculatus__subject__38197.0: assigning states
  [223/354] Peromyscus_maniculatus__subject__38198.0: assigning states
  [224/354] Peromyscus_maniculatus__subject__38199.0: assigning states
  [225/354] Peromyscus_maniculatus__subject__38200.0: assigning states
  [226/354] Peromyscus_maniculatus__subject__38201.0: assigning states
  [227/354] Peromyscus_maniculatus__subject__38208.0: assigning states
  [228/354] Peromyscus_maniculatus__subject__38209.0: assigning states
  [229/354] Peromyscus_maniculatus__subject__38235.0: assigning states
  [230/354] Peromyscus_maniculatus__subject__38246.0: assigning states
  [231/354] Peromyscus_maniculatus__subject__38285.0: assigning states
  [232/354] Peromyscus_maniculatus__subject__38286.0: assigning states
  [233/354] Peromyscus_maniculatus__subject__38298.0: assigning states
  [234/354] Peromyscus_maniculatus__subject__38299.0: assigning states
  [235/354] Peromyscus_maniculatus__subject__38300.0: assigning states
  [236/354] Peromyscus_maniculatus__subject__38301.0: assigning states
  [237/354] Peromyscus_maniculatus__subject__38308.0: assigning states
  [238/354] Peromyscus_maniculatus__subject__38309.0: assigning states
  [239/354] Peromyscus_maniculatus__subject__38310.0: assigning states
  [240/354] Peromyscus_maniculatus__subject__38311.0: assigning states
  [241/354] Peromyscus_maniculatus__subject__38312.0: assigning states
  [242/354] Peromyscus_maniculatus__subject__38313.0: assigning states
  [243/354] Peromyscus_maniculatus__subject__38314.0: assigning states
  [244/354] Peromyscus_maniculatus__subject__38323.0: assigning states
  [245/354] Peromyscus_maniculatus__subject__38324.0: assigning states
  [246/354] Peromyscus_maniculatus__subject__38407.0: assigning states
  [247/354] Peromyscus_maniculatus__subject__38408.0: assigning states
  [248/354] Peromyscus_maniculatus__subject__38409.0: assigning states
  [249/354] Peromyscus_maniculatus__subject__38410.0: assigning states
  [250/354] Peromyscus_maniculatus__subject__38411.0: assigning states
  [251/354] Peromyscus_maniculatus__subject__38412.0: assigning states
  [252/354] Peromyscus_maniculatus__subject__38413.0: assigning states
  [253/354] Peromyscus_maniculatus__subject__38427.0: assigning states
  [254/354] Peromyscus_maniculatus__subject__38428.0: assigning states
  [255/354] Peromyscus_maniculatus__subject__38429.0: assigning states
  [256/354] Peromyscus_maniculatus__subject__38430.0: assigning states
  [257/354] Peromyscus_maniculatus__subject__38431.0: assigning states
  [258/354] Peromyscus_maniculatus__subject__38508.0: assigning states
  [259/354] Peromyscus_maniculatus__subject__38509.0: assigning states
  [260/354] Peromyscus_maniculatus__subject__38510.0: assigning states
  [261/354] Peromyscus_maniculatus__subject__38517.0: assigning states
  [262/354] Peromyscus_maniculatus__subject__38518.0: assigning states
  [263/354] Peromyscus_maniculatus__subject__38531.0: assigning states
  [264/354] Peromyscus_maniculatus__subject__38532.0: assigning states
  [265/354] Peromyscus_maniculatus__subject__38569.0: assigning states
  [266/354] Peromyscus_maniculatus__subject__38572.0: assigning states
  [267/354] Peromyscus_maniculatus__subject__38573.0: assigning states
  [268/354] Peromyscus_maniculatus__subject__38574.0: assigning states
  [269/354] Peromyscus_maniculatus__subject__38575.0: assigning states
  [270/354] Peromyscus_maniculatus__subject__38576.0: assigning states
  [271/354] Peromyscus_maniculatus__subject__38591.0: assigning states
  [272/354] Peromyscus_maniculatus__subject__38648.0: assigning states
  [273/354] Peromyscus_maniculatus__subject__38649.0: assigning states
  [274/354] Peromyscus_maniculatus__subject__38779.0: assigning states
  [275/354] Peromyscus_maniculatus__subject__38811.0: assigning states
  [276/354] Peromyscus_maniculatus__subject__38812.0: assigning states
  [277/354] Peromyscus_maniculatus__subject__38888.0: assigning states
  [278/354] Peromyscus_maniculatus__subject__38889.0: assigning states
  [279/354] Peromyscus_maniculatus__subject__38890.0: assigning states
  [280/354] Peromyscus_maniculatus__subject__38892.0: assigning states
  [281/354] Peromyscus_maniculatus__subject__39006.0: assigning states
  [282/354] Peromyscus_maniculatus__subject__39007.0: assigning states
  [283/354] Peromyscus_maniculatus__subject__39009.0: assigning states
  [284/354] Peromyscus_maniculatus__subject__39010.0: assigning states
  [285/354] Peromyscus_maniculatus__subject__39012.0: assigning states
  [286/354] Peromyscus_maniculatus__subject__39013.0: assigning states
  [287/354] Peromyscus_maniculatus__subject__39014.0: assigning states
  [288/354] Peromyscus_maniculatus__subject__39019.0: assigning states
  [289/354] Peromyscus_maniculatus__subject__39020.0: assigning states
  [290/354] Peromyscus_maniculatus__subject__39043.0: assigning states
  [291/354] Peromyscus_maniculatus__subject__39044.0: assigning states